In [9]:
import os
from datetime import datetime
import pandas as pd
from tqdm import tqdm

tqdm.pandas()

In [10]:
import re

def categoria_proj(nome_arquivo):
    # Define os padrões e as categorias correspondentes
    categorias = {
        "REDE": r"\bREDE\b",
        "PREF": r"\bPREF\b",
        "MAP": r"\bMAP\b",
        "TOP": r"\bTOP\b",
        "CAD": r"\bCAD\b",
        "SPT": r"\bSPT\b",
        "CAD": r"\bAS BILT\b",
        "CAD": r"\bAS BUILT\b",
        "RAMAL": r"\bRAMAL\b",
        "PLANO DE FURO": r"\bPF\b"
    }
    
    # Verifica qual padrão corresponde ao nome do arquivo
    for categoria, padrao in categorias.items():
        if re.search(padrao, nome_arquivo):
            return categoria
    
    # Retorna "Não definido" caso não encontre uma categoria
    return "Não definido"

In [11]:
def obter_informacoes_arquivos(pasta):
    informacoes_arquivos = []

    for pasta_atual, sub_pastas, arquivos in tqdm(os.walk(pasta)):
        for arquivo in arquivos:
            caminho_completo = os.path.join(pasta_atual, arquivo)

            try:
                info = os.stat(caminho_completo)
            except (PermissionError, FileNotFoundError) as e:
                # Lidar com exceções (pular o arquivo e imprimir uma mensagem, se desejar)
                print(f"Erro ao obter informações de {caminho_completo}: {e}")
                continue

            # Extrair informações desejadas
            caminho_arquivo = caminho_completo
            arquivo, tipo_arquivo = os.path.splitext(arquivo)
            autor = info.st_uid
            data_criacao = datetime.fromtimestamp(info.st_ctime).strftime("%d/%m/%Y %H:%M")
            tempo_acesso = datetime.fromtimestamp(info.st_atime).strftime("%d/%m/%Y %H:%M")
            tempo_modificacao = datetime.fromtimestamp(info.st_mtime).strftime("%d/%m/%Y %H:%M")
            tempo_mudanca = datetime.fromtimestamp(info.st_ctime).strftime("%d/%m/%Y %H:%M")
            tamanho_arquivo = info.st_size,
            tipo_proj = categoria_proj(arquivo)

            # Criar um dicionário com as informações
            informacao_arquivo = {
                'caminho': caminho_arquivo,
                'arquivo': arquivo,
                'tipo_arquivo': tipo_arquivo,
                'tipo_proj': tipo_proj,
                'data_criacao': data_criacao,
                'tempo_acesso': tempo_acesso,
                'tempo_modificacao': tempo_modificacao,
                'tempo_mudanca': tempo_mudanca,
                'tamanho': tamanho_arquivo
            }

            # Adicionar à lista de informações
            informacoes_arquivos.append(informacao_arquivo)
    print(informacoes_arquivos)
    return informacoes_arquivos

In [12]:
def criar_pasta_do_dia(df, caminho_base, nome):
    # Obtém a data atual
    data_atual = datetime.now()

    # Formata a data como YYYYMMDD
    data = data_atual.strftime("%Y-%m-%d")
    data_hora = data_atual.strftime("%Y-%m-%d_%H.%M.%S")

    # Constrói o caminho da pasta do dia
    caminho_pasta_do_dia = os.path.join(caminho_base, data)

    # Cria a pasta se ela não existir
    if not os.path.exists(caminho_pasta_do_dia):
        os.makedirs(caminho_pasta_do_dia)

    # Constrói o nome do arquivo com a data
    nome_arquivo = f'{caminho_pasta_do_dia}\{data_hora} - {nome}.csv'

    # Salva o DataFrame no arquivo
    df.to_csv(nome_arquivo)

    return df.to_csv(nome_arquivo)

<string>:17: SyntaxWarning: invalid escape sequence '\{'
<>:17: SyntaxWarning: invalid escape sequence '\{'
<string>:17: SyntaxWarning: invalid escape sequence '\{'
<>:17: SyntaxWarning: invalid escape sequence '\{'
C:\Users\lucas.almeida\AppData\Local\Temp\ipykernel_12252\4020651832.py:17: SyntaxWarning: invalid escape sequence '\{'
  nome_arquivo = f'{caminho_pasta_do_dia}\{data_hora} - {nome}.csv'

In [13]:
caminho = ['C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS', "P:\\PROJETOS"]
nome = ['CESAN 2025', 'CESAN 2025 BACKUP']

Pastas = {
  'nome': nome,
  'caminho': caminho
}

Pastas_df = pd.DataFrame(Pastas)

for index, row in tqdm(Pastas_df.iterrows()):

  informacoes = obter_informacoes_arquivos(row['caminho'])

  informacoes_df = pd.DataFrame(informacoes)
  informacoes_df['tamanho'] = informacoes_df['tamanho'].apply(lambda x: x[0] if isinstance(x, tuple) else x)
  informacoes_df['tamanho_kb'] = round(informacoes_df['tamanho']/1024, 2)

  display(informacoes_df)

  informacoes_df = informacoes_df.sort_values(by='tipo_arquivo')
  print(informacoes_df['tipo_arquivo'].unique())

  nome = row['nome']
  caminho_pasta_do_dia = criar_pasta_do_dia(informacoes_df, '.\database\list files', nome)

<>:25: SyntaxWarning: invalid escape sequence '\d'
<>:25: SyntaxWarning: invalid escape sequence '\d'
C:\Users\lucas.almeida\AppData\Local\Temp\ipykernel_12252\3727444524.py:25: SyntaxWarning: invalid escape sequence '\d'
  caminho_pasta_do_dia = criar_pasta_do_dia(informacoes_df, '.\database\list files', nome)
0it [00:00, ?it/s]

Erro ao obter informações de C:\Users\lucas.almeida\OneDrive - Sanit\10002 - CENSAN PLANEJAMENTO\PROJETOS\02. VITÓRIA\03. PRAIA DO CANTO\02. Mapa Iluminado\MAP - 2024-10-02\CUsersjulia.barbosaOneDrive - SanitCESANPROJETOS03. PRAIA DO CANTO10. Mapa IluminadoMAP - 2024-09-30praia do canto.kml: [WinError 3] O sistema não pode encontrar o caminho especificado: 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\MAP - 2024-10-02\\CUsersjulia.barbosaOneDrive - SanitCESANPROJETOS03. PRAIA DO CANTO10. Mapa IluminadoMAP - 2024-09-30praia do canto.kml'
Erro ao obter informações de C:\Users\lucas.almeida\OneDrive - Sanit\10002 - CENSAN PLANEJAMENTO\PROJETOS\02. VITÓRIA\04. CENTRO\05. Plano de Furo\2024-08-22\ENC_ Compilado Planos de Furo\PF Av Pres Florentino\PF Av Pres Florentino\08.11.01.2024 - AV.PRES FLORENTINO AVIDOS - FL01 REV00.pdf: [WinError 3] O sistema não pode encontrar o caminho especificado: 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\02. VITÓRIA\\04. CENTRO\\05. Plano de Furo\\2024-08-22\\ENC_ Compilado Planos de Furo\\PF Av Pres Florentino\\PF Av Pres Florentino\\08.11.01.2024 - AV.PRES FLORENTINO AVIDOS - FL01 REV00.pdf'
Erro ao obter informações de C:\Users\lucas.almeida\OneDrive - Sanit\10002 - CENSAN PLANEJAMENTO\PROJETOS\02. VITÓRIA\04. CENTRO\05. Plano de Furo\2024-08-22\ENC_ Compilado Planos de Furo\PF Av Pres Florentino\PF Av Pres Florentino\08.11.01.2024 - AV.PRES FLORENTINO AVIDOS - FL02 REV00.pdf: [WinError 3] O sistema não pode encontrar o caminho especificado: 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\02. VITÓRIA\\04. CENTRO\\05. Plano de Furo\\2024-08-22\\ENC_ Compilado Planos de Furo\\PF Av Pres Florentino\\PF Av Pres Florentino\\08.11.01.2024 - AV.PRES FLORENTINO AVIDOS - FL02 REV00.pdf'
Erro ao obter informações de C:\Users\lucas.almeida\OneDrive - Sanit\10002 - CENSAN PLANEJAMENTO\PROJETOS\02. VITÓRIA\04. CENTRO\05. Plano de Furo\2024-08-22\ENC_ Compilado Planos de Furo\PF Av Pres Florentino\PF Av Pres Florentino\08.11.01.2024 - AV.PRES FLORENTINO AVIDOS - FL03 REV00.pdf: [WinError 3] O sistema não pode encontrar o caminho especificado: 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\02. VITÓRIA\\04. CENTRO\\05. Plano de Furo\\2024-08-22\\ENC_ Compilado Planos de Furo\\PF Av Pres Florentino\\PF Av Pres Florentino\\08.11.01.2024 - AV.PRES FLORENTINO AVIDOS - FL03 REV00.pdf'
Erro ao obter informações de C:\Users\lucas.almeida\OneDrive - Sanit\10002 - CENSAN PLANEJAMENTO\PROJETOS\02. VITÓRIA\04. CENTRO\05. Plano de Furo\2024-08-22\ENC_ Compilado Planos de Furo\PF Av Pres Florentino\PF Av Pres Florentino\08.11.01.2024 - AV.PRES FLORENTINO AVIDOS - FL04 REV00.pdf: [WinError 3] O sistema não pode encontrar o caminho especificado: 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\02. VITÓRIA\\04. CENTRO\\05. Plano de Furo\\2024-08-22\\ENC_ Compilado Planos de Furo\\PF Av Pres Florentino\\PF Av Pres Florentino\\08.11.01.2024 - AV.PRES FLORENTINO AVIDOS - FL04 REV00.pdf'
Erro ao obter informações de C:\Users\lucas.almeida\OneDrive - Sanit\10002 - CENSAN PLANEJAMENTO\PROJETOS\02. VITÓRIA\04. CENTRO\05. Plano de Furo\2024-08-22\ENC_ Compilado Planos de Furo\PF Av Pres Florentino\PF Av Pres Florentino\08.11.01.2024 - AV.PRES FLORENTINO AVIDOS - FL05 REV00.pdf: [WinError 3] O sistema não pode encontrar o caminho especificado: 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\02. VITÓRIA\\04. CENTRO\\05. Plano de Furo\\2024-08-22\\ENC_ Compilado Planos de Furo\\PF Av Pres Florentino\\PF Av Pres Florentino\\08.11.01.2024 - AV.PRES FLORENTINO AVIDOS - FL05 REV00.pdf'
Erro ao obter informações de C:\Users\lucas.almeida\OneDrive - Sanit\10002 - CENSAN PLANEJAMENTO\PROJETOS\02. VITÓRIA\04. CENTRO\05. Plano de Furo\2024-08-22\ENC_ Compilado Planos de Furo\PF Av Pres Florentino\PF Av Pres Florentino\08.11.01.2024 - AV.PRES FLORENTINO AVIDOS - FL06 REV00.pdf: [WinError 3] O sistema não pode encontrar o caminho especificado: 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\02. VITÓRIA\\04. CENTRO\\05. Plano de Furo\\2024-08-22\\ENC_ Compilado Planos de Furo\\PF Av Pres Florentino\\PF Av Pres Florentino\\08.11.01.2024 - AV.PRES FLORENTINO AVIDOS - FL06 REV00.pdf'

420it [00:00, 835.84it/s]

[{'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\Controle de interligação.xlsx', 'arquivo': 'Controle de interligação', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:20', 'tempo_modificacao': '13/11/2024 22:10', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (22330,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\Controle_dos_Relatórios_de_Furo_2025-01-20_1.xlsx', 'arquivo': 'Controle_dos_Relatórios_de_Furo_2025-01-20_1', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 14:22', 'tempo_acesso': '22/01/2025 14:22', 'tempo_modificacao': '20/01/2025 17:38', 'tempo_mudanca': '22/01/2025 14:22', 'tamanho': (66149,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\Controle_dos_Relatórios_de_Furo_2025-01-22.xlsx', 'arquivo': 'Controle_dos_Relatórios_de_Furo_2025-01-22', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '23/01/2025 08:39', 'tempo_acesso': '23/01/2025 08:39', 'tempo_modificacao': '24/01/2025 17:26', 'tempo_mudanca': '23/01/2025 08:39', 'tamanho': (66344,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\CT 066-2024-R03.kmz', 'arquivo': 'CT 066-2024-R03', 'tipo_arquivo': '.kmz', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '23/01/2025 00:34', 'tempo_modificacao': '23/08/2024 10:09', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (2959155,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\desktop.ini', 'arquivo': 'desktop', 'tipo_arquivo': '.ini', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 11:07', 'tempo_acesso': '27/01/2025 00:13', 'tempo_modificacao': '03/10/2024 21:01', 'tempo_mudanca': '22/01/2025 11:07', 'tamanho': (105,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\FICHA DEMANDA TOPOGRAFIA.xlsx', 'arquivo': 'FICHA DEMANDA TOPOGRAFIA', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:20', 'tempo_modificacao': '08/01/2025 18:01', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (13420,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\FRENTE DE OBRAS x RUAS x COMPARATIVO 2025-01-17.xlsx', 'arquivo': 'FRENTE DE OBRAS x RUAS x COMPARATIVO 2025-01-17', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 14:22', 'tempo_acesso': '22/01/2025 14:22', 'tempo_modificacao': '22/01/2025 18:12', 'tempo_mudanca': '22/01/2025 14:22', 'tamanho': (31077,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\FRENTE DE OBRAS x RUAS x COMPARATIVO 2025-01-22.xlsx', 'arquivo': 'FRENTE DE OBRAS x RUAS x COMPARATIVO 2025-01-22', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 18:37', 'tempo_acesso': '22/01/2025 18:37', 'tempo_modificacao': '22/01/2025 18:14', 'tempo_mudanca': '22/01/2025 18:37', 'tamanho': (30997,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\FRENTE DE OBRAS x RUAS.xlsx', 'arquivo': 'FRENTE DE OBRAS x RUAS', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:20', 'tempo_modificacao': '25/11/2024 11:03', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (12900,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\plot.log', 'arquivo': 'plot', 'tipo_arquivo': '.log', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '22/10/2024 08:22', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (412,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\Produção Ramal.xlsx', 'arquivo': 'Produção Ramal', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '23/01/2025 00:35', 'tempo_modificacao': '12/11/2024 13:33', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (2990527,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\REDE-PROJETO E CADASTRO-R04.xlsx', 'arquivo': 'REDE-PROJETO E CADASTRO-R04', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'REDE', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:20', 'tempo_modificacao': '31/10/2024 10:46', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (42702,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\SPT CONTROLE.xlsx', 'arquivo': 'SPT CONTROLE', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'SPT', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:21', 'tempo_modificacao': '14/11/2024 13:43', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (91761,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\SS CESAN.xlsx', 'arquivo': 'SS CESAN', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:20', 'tempo_modificacao': '31/10/2024 16:16', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (33644,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\SS CT066-2024 Rev01.xlsx', 'arquivo': 'SS CT066-2024 Rev01', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:20', 'tempo_modificacao': '30/10/2024 10:37', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (13779,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\SS CT066-2024 Rev02.xlsx', 'arquivo': 'SS CT066-2024 Rev02', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:20', 'tempo_modificacao': '23/12/2024 11:01', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (13827,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\SS CT066-2024 Rev03.xlsx', 'arquivo': 'SS CT066-2024 Rev03', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:20', 'tempo_modificacao': '24/01/2025 17:24', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (18000,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\SS CT066-2024.pdf', 'arquivo': 'SS CT066-2024', 'tipo_arquivo': '.pdf', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:21', 'tempo_modificacao': '18/10/2024 09:45', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (58306,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\SS CT066-2024.xlsx', 'arquivo': 'SS CT066-2024', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:20', 'tempo_modificacao': '29/10/2024 11:20', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (13874,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\STATUS PROJETOS-R01.xlsx', 'arquivo': 'STATUS PROJETOS-R01', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:20', 'tempo_modificacao': '08/11/2024 18:33', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (12711,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\STATUS PROJETOS.xlsx', 'arquivo': 'STATUS PROJETOS', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:19', 'tempo_modificacao': '03/10/2024 17:34', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (10786,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\VIT-REDE-CADASTRO-R00.xlsx', 'arquivo': 'VIT-REDE-CADASTRO-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'REDE', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:31', 'tempo_modificacao': '03/10/2024 23:00', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (301204,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\VIT-REDE-GERAL-R00.xlsx', 'arquivo': 'VIT-REDE-GERAL-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'REDE', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:31', 'tempo_modificacao': '16/10/2024 07:50', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (301245,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\VIT-REDE-PROJETOS-R05.xlsm', 'arquivo': 'VIT-REDE-PROJETOS-R05', 'tipo_arquivo': '.xlsm', 'tipo_proj': 'REDE', 'data_criacao': '22/01/2025 10:55', 'tempo_acesso': '22/01/2025 23:23', 'tempo_modificacao': '20/12/2024 16:06', 'tempo_mudanca': '22/01/2025 10:55', 'tamanho': (141345,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\app.json', 'arquivo': 'app', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '19/12/2024 09:02', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (154,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\appearance.json', 'arquivo': 'appearance', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '19/12/2024 09:02', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (133,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\community-plugins.json', 'arquivo': 'community-plugins', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '19/12/2024 09:03', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (271,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\core-plugins-migration.json', 'arquivo': 'core-plugins-migration', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '21/10/2024 09:44', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (649,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\core-plugins.json', 'arquivo': 'core-plugins', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '19/12/2024 09:02', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (649,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\graph.json', 'arquivo': 'graph', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '04/12/2024 10:22', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (511,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\hotkeys.json', 'arquivo': 'hotkeys', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:17', 'tempo_acesso': '22/01/2025 23:17', 'tempo_modificacao': '19/04/2023 13:48', 'tempo_mudanca': '22/01/2025 23:17', 'tamanho': (2,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\page-preview.json', 'arquivo': 'page-preview', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '21/06/2024 09:12', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (21,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\types.json', 'arquivo': 'types', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '19/12/2024 09:03', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (891,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\workspace.json', 'arquivo': 'workspace', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:19', 'tempo_acesso': '22/01/2025 23:19', 'tempo_modificacao': '19/12/2024 09:03', 'tempo_mudanca': '22/01/2025 23:19', 'tamanho': (9760,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\workspaces.json', 'arquivo': 'workspaces', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:19', 'tempo_acesso': '22/01/2025 23:19', 'tempo_modificacao': '16/07/2024 13:00', 'tempo_mudanca': '22/01/2025 23:19', 'tamanho': (5490,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\calendar\\data.json', 'arquivo': 'data', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '19/12/2024 09:02', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (231,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\calendar\\main.js', 'arquivo': 'main', 'tipo_arquivo': '.js', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:23', 'tempo_acesso': '22/01/2025 23:23', 'tempo_modificacao': '21/06/2024 09:07', 'tempo_mudanca': '22/01/2025 23:23', 'tamanho': (141498,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\calendar\\manifest.json', 'arquivo': 'manifest', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '21/06/2024 09:07', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (249,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\dataview\\main.js', 'arquivo': 'main', 'tipo_arquivo': '.js', 'tipo_proj': 'Não definido', 'data_criacao': '23/01/2025 00:24', 'tempo_acesso': '23/01/2025 00:24', 'tempo_modificacao': '21/06/2024 09:06', 'tempo_mudanca': '23/01/2025 00:24', 'tamanho': (2364918,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\dataview\\manifest.json', 'arquivo': 'manifest', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '21/06/2024 09:06', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (357,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\dataview\\styles.css', 'arquivo': 'styles', 'tipo_arquivo': '.css', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:19', 'tempo_acesso': '22/01/2025 23:22', 'tempo_modificacao': '21/06/2024 09:07', 'tempo_mudanca': '22/01/2025 23:19', 'tamanho': (3159,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\obsidian-excalidraw-plugin\\data.json', 'arquivo': 'data', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:20', 'tempo_acesso': '22/01/2025 23:20', 'tempo_modificacao': '16/07/2024 14:54', 'tempo_mudanca': '22/01/2025 23:20', 'tamanho': (19060,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\obsidian-excalidraw-plugin\\main.js', 'arquivo': 'main', 'tipo_arquivo': '.js', 'tipo_proj': 'Não definido', 'data_criacao': '23/01/2025 01:13', 'tempo_acesso': '23/01/2025 01:13', 'tempo_modificacao': '16/07/2024 13:00', 'tempo_mudanca': '23/01/2025 01:13', 'tamanho': (4669052,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\obsidian-excalidraw-plugin\\manifest.json', 'arquivo': 'manifest', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '16/07/2024 13:00', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (415,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\obsidian-excalidraw-plugin\\styles.css', 'arquivo': 'styles', 'tipo_arquivo': '.css', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:38', 'tempo_acesso': '22/01/2025 23:38', 'tempo_modificacao': '16/07/2024 13:00', 'tempo_mudanca': '22/01/2025 23:38', 'tamanho': (450542,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\obsidian-icon-folder\\data.json', 'arquivo': 'data', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '19/12/2024 09:02', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (720,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\obsidian-icon-folder\\main.js', 'arquivo': 'main', 'tipo_arquivo': '.js', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:56', 'tempo_acesso': '22/01/2025 23:56', 'tempo_modificacao': '21/06/2024 09:59', 'tempo_mudanca': '22/01/2025 23:56', 'tamanho': (969042,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\obsidian-icon-folder\\manifest.json', 'arquivo': 'manifest', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '21/06/2024 09:59', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (311,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\obsidian-icon-folder\\styles.css', 'arquivo': 'styles', 'tipo_arquivo': '.css', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:19', 'tempo_acesso': '22/01/2025 23:22', 'tempo_modificacao': '21/06/2024 09:59', 'tempo_mudanca': '22/01/2025 23:19', 'tamanho': (2155,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\obsidian-icons-plugin\\data.json', 'arquivo': 'data', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '21/06/2024 09:59', 'tempo_mudanca': '22/01/2025 23:18', 'tamanho': (108,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\obsidian-icons-plugin\\main.js', 'arquivo': 'main', 'tipo_arquivo': '.js', 'tipo_proj': 'Não definido', 'data_criacao': '23/01/2025 01:55', 'tempo_acesso': '23/01/2025 01:56', 'tempo_modificacao': '21/06/2024 09:11', 'tempo_mudanca': '23/01/2025 01:55', 'tamanho': (8944025,)}, {'caminho': 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS\\.obsidian\\plugins\\obsidian-icons-plugin\\manifest.json', 'arquivo': 'manifest', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '22/01/2025 23:18', 'tempo_acesso': '22/01/2025 23:18', 'tempo_modificacao': '21/06/202

,caminho,arquivo,tipo_arquivo,tipo_proj,data_criacao,tempo_acesso,tempo_modificacao,tempo_mudanca,tamanho,tamanho_kb
0,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,Controle de interligação,.xlsx,Não definido,22/01/2025 10:55,22/01/2025 23:20,13/11/2024 22:10,22/01/2025 10:55,22330,21.81
1,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,Controle_dos_Relatórios_de_Furo_2025-01-20_1,.xlsx,Não definido,22/01/2025 14:22,22/01/2025 14:22,20/01/2025 17:38,22/01/2025 14:22,66149,64.60
2,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,Controle_dos_Relatórios_de_Furo_2025-01-22,.xlsx,Não definido,23/01/2025 08:39,23/01/2025 08:39,24/01/2025 17:26,23/01/2025 08:39,66344,64.79
3,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,CT 066-2024-R03,.kmz,Não definido,22/01/2025 10:55,23/01/2025 00:34,23/08/2024 10:09,22/01/2025 10:55,2959155,2889.80
4,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,desktop,.ini,Não definido,22/01/2025 11:07,27/01/2025 00:13,03/10/2024 21:01,22/01/2025 11:07,105,0.10
...,...,...,...,...,...,...,...,...,...,...
3989,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-ASF-BM02-LEITÃO DA SILVA-R03,.dwg,Não definido,22/01/2025 10:56,22/01/2025 23:52,01/11/2024 14:29,22/01/2025 10:56,671705,655.96
3990,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-ASF-BM03-LEITÃO DA SILVA-R03,.bak,Não definido,22/01/2025 23:52,22/01/2025 23:52,30/10/2024 15:44,22/01/2025 23:52,671290,655.56
3991,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-ASF-BM03-LEITÃO DA SILVA-R03,.dwg,Não definido,22/01/2025 10:56,22/01/2025 23:53,01/11/2024 14:22,22/01/2025 10:56,672762,656.99
3992,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-ASF-BM05-LEITÃO DA SILVA-R03,.bak,Não definido,22/01/2025 23:52,22/01/2025 23:52,30/10/2024 15:12,22/01/2025 23:52,671386,655.65
3993,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-ASF-BM05-LEITÃO DA SILVA-R03,.dwg,Não definido,22/01/2025 10:56,22/01/2025 23:52,30/10/2024 15:44,22/01/2025 10:56,671290,655.56

1it [00:00,  1.64it/s]

['' '.INI' '.JPG' '.PDF' '.PNG' '.TXT' '.VCL' '.bak' '.canvas' '.chm'
 '.cor' '.css' '.csv' '.ctb' '.cuix' '.db' '.dll' '.docx' '.dsd' '.dwg'
 '.dwl' '.dxf' '.eml' '.exe' '.gis' '.ini' '.iprb' '.iprh' '.jpeg' '.jpg'
 '.js' '.json' '.jxl' '.kml' '.kmz' '.log' '.md' '.mnr' '.mnu' '.mp4'
 '.mrk' '.pdf' '.png' '.pod' '.pptx' '.sig' '.time' '.tmp' '.txt' '.xlsm'
 '.xlsx' '.xml' '.zip']

446it [05:55,  1.25it/s]

[{'caminho': 'P:\\PROJETOS\\21218301.zip', 'arquivo': '21218301', 'tipo_arquivo': '.zip', 'tipo_proj': 'Não definido', 'data_criacao': '09/01/2025 12:48', 'tempo_acesso': '09/01/2025 12:48', 'tempo_modificacao': '17/12/2024 10:27', 'tempo_mudanca': '09/01/2025 12:48', 'tamanho': (1514622640,)}, {'caminho': 'P:\\PROJETOS\\Controle de interligação.xlsx', 'arquivo': 'Controle de interligação', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:35', 'tempo_acesso': '17/12/2024 09:35', 'tempo_modificacao': '13/11/2024 22:10', 'tempo_mudanca': '17/12/2024 09:35', 'tamanho': (22330,)}, {'caminho': 'P:\\PROJETOS\\CT 066-2024-R03.kmz', 'arquivo': 'CT 066-2024-R03', 'tipo_arquivo': '.kmz', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:35', 'tempo_acesso': '17/12/2024 09:35', 'tempo_modificacao': '23/08/2024 10:09', 'tempo_mudanca': '17/12/2024 09:35', 'tamanho': (2959155,)}, {'caminho': 'P:\\PROJETOS\\desktop.ini', 'arquivo': 'desktop', 'tipo_arquivo': '.ini', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:35', 'tempo_acesso': '17/12/2024 09:35', 'tempo_modificacao': '03/10/2024 21:01', 'tempo_mudanca': '17/12/2024 09:35', 'tamanho': (105,)}, {'caminho': 'P:\\PROJETOS\\FICHA DEMANDA TOPOGRAFIA.xlsx', 'arquivo': 'FICHA DEMANDA TOPOGRAFIA', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '09/01/2025 13:06', 'tempo_acesso': '09/01/2025 13:06', 'tempo_modificacao': '08/01/2025 18:01', 'tempo_mudanca': '09/01/2025 13:06', 'tamanho': (13420,)}, {'caminho': 'P:\\PROJETOS\\FRENTE DE OBRAS x RUAS.xlsx', 'arquivo': 'FRENTE DE OBRAS x RUAS', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:35', 'tempo_acesso': '17/12/2024 09:35', 'tempo_modificacao': '25/11/2024 11:03', 'tempo_mudanca': '17/12/2024 09:35', 'tamanho': (12900,)}, {'caminho': 'P:\\PROJETOS\\Plano de Furo - PF.zip', 'arquivo': 'Plano de Furo - PF', 'tipo_arquivo': '.zip', 'tipo_proj': 'PLANO DE FURO', 'data_criacao': '09/01/2025 13:06', 'tempo_acesso': '09/01/2025 13:06', 'tempo_modificacao': '21/10/2024 11:14', 'tempo_mudanca': '09/01/2025 13:06', 'tamanho': (250737858,)}, {'caminho': 'P:\\PROJETOS\\plot.log', 'arquivo': 'plot', 'tipo_arquivo': '.log', 'tipo_proj': 'Não definido', 'data_criacao': '09/01/2025 13:08', 'tempo_acesso': '09/01/2025 13:08', 'tempo_modificacao': '22/10/2024 08:22', 'tempo_mudanca': '09/01/2025 13:08', 'tamanho': (412,)}, {'caminho': 'P:\\PROJETOS\\Produção Ramal.xlsx', 'arquivo': 'Produção Ramal', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '12/11/2024 13:33', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (2990527,)}, {'caminho': 'P:\\PROJETOS\\REDE-PROJETO E CADASTRO-R04.xlsx', 'arquivo': 'REDE-PROJETO E CADASTRO-R04', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'REDE', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '31/10/2024 10:46', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (42702,)}, {'caminho': 'P:\\PROJETOS\\SPT CONTROLE.xlsx', 'arquivo': 'SPT CONTROLE', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'SPT', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '14/11/2024 13:43', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (91761,)}, {'caminho': 'P:\\PROJETOS\\SS CESAN.xlsx', 'arquivo': 'SS CESAN', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '31/10/2024 16:16', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (33644,)}, {'caminho': 'P:\\PROJETOS\\SS CT066-2024 Rev01.xlsx', 'arquivo': 'SS CT066-2024 Rev01', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '30/10/2024 10:37', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (13779,)}, {'caminho': 'P:\\PROJETOS\\SS CT066-2024 Rev02.xlsx', 'arquivo': 'SS CT066-2024 Rev02', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '23/12/2024 11:01', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (13827,)}, {'caminho': 'P:\\PROJETOS\\SS CT066-2024 Rev03.xlsx', 'arquivo': 'SS CT066-2024 Rev03', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '09/01/2025 13:09', 'tempo_acesso': '09/01/2025 13:09', 'tempo_modificacao': '06/01/2025 16:45', 'tempo_mudanca': '09/01/2025 13:09', 'tamanho': (17970,)}, {'caminho': 'P:\\PROJETOS\\SS CT066-2024.pdf', 'arquivo': 'SS CT066-2024', 'tipo_arquivo': '.pdf', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '18/10/2024 09:45', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (58306,)}, {'caminho': 'P:\\PROJETOS\\SS CT066-2024.xlsx', 'arquivo': 'SS CT066-2024', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '29/10/2024 11:20', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (13874,)}, {'caminho': 'P:\\PROJETOS\\STATUS PROJETOS-R01.xlsx', 'arquivo': 'STATUS PROJETOS-R01', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '08/11/2024 18:33', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (12711,)}, {'caminho': 'P:\\PROJETOS\\STATUS PROJETOS.xlsx', 'arquivo': 'STATUS PROJETOS', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '03/10/2024 17:34', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (10786,)}, {'caminho': 'P:\\PROJETOS\\VIT-REDE-CADASTRO-R00.xlsx', 'arquivo': 'VIT-REDE-CADASTRO-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'REDE', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '03/10/2024 23:00', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (301204,)}, {'caminho': 'P:\\PROJETOS\\VIT-REDE-GERAL-R00.xlsx', 'arquivo': 'VIT-REDE-GERAL-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'REDE', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/10/2024 07:50', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (301245,)}, {'caminho': 'P:\\PROJETOS\\VIT-REDE-PROJETOS-R05.xlsm', 'arquivo': 'VIT-REDE-PROJETOS-R05', 'tipo_arquivo': '.xlsm', 'tipo_proj': 'REDE', 'data_criacao': '09/01/2025 13:09', 'tempo_acesso': '09/01/2025 13:09', 'tempo_modificacao': '20/12/2024 16:06', 'tempo_mudanca': '09/01/2025 13:09', 'tamanho': (141345,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\app.json', 'arquivo': 'app', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '19/12/2024 09:02', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (154,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\appearance.json', 'arquivo': 'appearance', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '19/12/2024 09:02', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (133,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\community-plugins.json', 'arquivo': 'community-plugins', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '19/12/2024 09:03', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (271,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\core-plugins-migration.json', 'arquivo': 'core-plugins-migration', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '21/10/2024 09:44', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (649,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\core-plugins.json', 'arquivo': 'core-plugins', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '19/12/2024 09:02', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (649,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\graph.json', 'arquivo': 'graph', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '04/12/2024 10:22', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (511,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\hotkeys.json', 'arquivo': 'hotkeys', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '19/04/2023 13:48', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (2,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\page-preview.json', 'arquivo': 'page-preview', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '21/06/2024 09:12', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (21,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\types.json', 'arquivo': 'types', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '19/12/2024 09:03', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (891,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\workspace.json', 'arquivo': 'workspace', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '19/12/2024 09:03', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (9760,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\workspaces.json', 'arquivo': 'workspaces', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 13:00', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (5490,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\calendar\\data.json', 'arquivo': 'data', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '19/12/2024 09:02', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (231,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\calendar\\main.js', 'arquivo': 'main', 'tipo_arquivo': '.js', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '21/06/2024 09:07', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (141498,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\calendar\\manifest.json', 'arquivo': 'manifest', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '21/06/2024 09:07', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (249,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\dataview\\main.js', 'arquivo': 'main', 'tipo_arquivo': '.js', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '21/06/2024 09:06', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (2364918,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\dataview\\manifest.json', 'arquivo': 'manifest', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '21/06/2024 09:06', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (357,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\dataview\\styles.css', 'arquivo': 'styles', 'tipo_arquivo': '.css', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '21/06/2024 09:07', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (3159,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-excalidraw-plugin\\data.json', 'arquivo': 'data', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 14:54', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (19060,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-excalidraw-plugin\\main.js', 'arquivo': 'main', 'tipo_arquivo': '.js', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 13:00', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (4669052,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-excalidraw-plugin\\manifest.json', 'arquivo': 'manifest', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 13:00', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (415,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-excalidraw-plugin\\styles.css', 'arquivo': 'styles', 'tipo_arquivo': '.css', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 13:00', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (450542,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-icon-folder\\data.json', 'arquivo': 'data', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '19/12/2024 09:02', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (720,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-icon-folder\\main.js', 'arquivo': 'main', 'tipo_arquivo': '.js', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '21/06/2024 09:59', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (969042,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-icon-folder\\manifest.json', 'arquivo': 'manifest', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '21/06/2024 09:59', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (311,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-icon-folder\\styles.css', 'arquivo': 'styles', 'tipo_arquivo': '.css', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '21/06/2024 09:59', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (2155,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-icons-plugin\\data.json', 'arquivo': 'data', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '21/06/2024 09:59', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (108,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-icons-plugin\\main.js', 'arquivo': 'main', 'tipo_arquivo': '.js', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '21/06/2024 09:11', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (8944025,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-icons-plugin\\manifest.json', 'arquivo': 'manifest', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '21/06/2024 09:11', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (259,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-icons-plugin\\styles.css', 'arquivo': 'styles', 'tipo_arquivo': '.css', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '21/06/2024 09:11', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (292,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-minimal-settings\\data.json', 'arquivo': 'data', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '19/12/2024 09:02', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (893,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-minimal-settings\\main.js', 'arquivo': 'main', 'tipo_arquivo': '.js', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 13:05', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (142054,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-minimal-settings\\manifest.json', 'arquivo': 'manifest', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 13:05', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (355,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-minimal-settings\\styles.css', 'arquivo': 'styles', 'tipo_arquivo': '.css', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 13:05', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (11,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-outliner\\main.js', 'arquivo': 'main', 'tipo_arquivo': '.js', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 14:56', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (459846,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-outliner\\manifest.json', 'arquivo': 'manifest', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 14:56', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (285,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-outliner\\styles.css', 'arquivo': 'styles', 'tipo_arquivo': '.css', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 14:56', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (2163,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-style-settings\\data.json', 'arquivo': 'data', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 13:08', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (230,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-style-settings\\main.js', 'arquivo': 'main', 'tipo_arquivo': '.js', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 13:07', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (337596,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-style-settings\\manifest.json', 'arquivo': 'manifest', 'tipo_arquivo': '.json', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 13:07', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (321,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\obsidian-style-settings\\styles.css', 'arquivo': 'styles', 'tipo_arquivo': '.css', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 13:07', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (13906,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\omnisearch\\main.js', 'arquivo': 'main', 'tipo_arquivo': '.js', 'tipo_proj': 'Não definido', 'data_criacao': '17/12/2024 09:37', 'tempo_acesso': '17/12/2024 09:37', 'tempo_modificacao': '16/07/2024 14:57', 'tempo_mudanca': '17/12/2024 09:37', 'tamanho': (606216,)}, {'caminho': 'P:\\PROJETOS\\.obsidian\\plugins\\omnisearch\\manifest.json', 'arquivo': 'manifest', 'tipo_arquivo': '.jso

,caminho,arquivo,tipo_arquivo,tipo_proj,data_criacao,tempo_acesso,tempo_modificacao,tempo_mudanca,tamanho,tamanho_kb
0,P:\PROJETOS\21218301.zip,21218301,.zip,Não definido,09/01/2025 12:48,09/01/2025 12:48,17/12/2024 10:27,09/01/2025 12:48,1514622640,1479123.67
1,P:\PROJETOS\Controle de interligação.xlsx,Controle de interligação,.xlsx,Não definido,17/12/2024 09:35,17/12/2024 09:35,13/11/2024 22:10,17/12/2024 09:35,22330,21.81
2,P:\PROJETOS\CT 066-2024-R03.kmz,CT 066-2024-R03,.kmz,Não definido,17/12/2024 09:35,17/12/2024 09:35,23/08/2024 10:09,17/12/2024 09:35,2959155,2889.80
3,P:\PROJETOS\desktop.ini,desktop,.ini,Não definido,17/12/2024 09:35,17/12/2024 09:35,03/10/2024 21:01,17/12/2024 09:35,105,0.10
4,P:\PROJETOS\FICHA DEMANDA TOPOGRAFIA.xlsx,FICHA DEMANDA TOPOGRAFIA,.xlsx,Não definido,09/01/2025 13:06,09/01/2025 13:06,08/01/2025 18:01,09/01/2025 13:06,13420,13.11
...,...,...,...,...,...,...,...,...,...,...
4062,P:\PROJETOS\RIKHELMY\VIT-ASF-BM02-LEITÃO DA SI...,VIT-ASF-BM02-LEITÃO DA SILVA-R03,.dwg,Não definido,09/01/2025 12:47,09/01/2025 12:47,01/11/2024 14:29,09/01/2025 12:47,671705,655.96
4063,P:\PROJETOS\RIKHELMY\VIT-ASF-BM03-LEITÃO DA SI...,VIT-ASF-BM03-LEITÃO DA SILVA-R03,.bak,Não definido,09/01/2025 12:47,09/01/2025 12:47,30/10/2024 15:44,09/01/2025 12:47,671290,655.56
4064,P:\PROJETOS\RIKHELMY\VIT-ASF-BM03-LEITÃO DA SI...,VIT-ASF-BM03-LEITÃO DA SILVA-R03,.dwg,Não definido,09/01/2025 12:47,09/01/2025 12:47,01/11/2024 14:22,09/01/2025 12:47,672762,656.99
4065,P:\PROJETOS\RIKHELMY\VIT-ASF-BM05-LEITÃO DA SI...,VIT-ASF-BM05-LEITÃO DA SILVA-R03,.bak,Não definido,09/01/2025 12:48,09/01/2025 12:48,30/10/2024 15:12,09/01/2025 12:48,671386,655.65
4066,P:\PROJETOS\RIKHELMY\VIT-ASF-BM05-LEITÃO DA SI...,VIT-ASF-BM05-LEITÃO DA SILVA-R03,.dwg,Não definido,09/01/2025 12:48,09/01/2025 12:48,30/10/2024 15:44,09/01/2025 12:48,671290,655.56

2it [05:56, 178.28s/it]

['' '.INI' '.JPG' '.PDF' '.PNG' '.TXT' '.VCL' '.bak' '.canvas' '.chm'
 '.cor' '.css' '.csv' '.ctb' '.cuix' '.db' '.dll' '.docx' '.dsd' '.dwg'
 '.dwl' '.dxf' '.eml' '.exe' '.gis' '.ini' '.iprb' '.iprh' '.jpeg' '.jpg'
 '.js' '.json' '.jxl' '.kml' '.kmz' '.log' '.md' '.mnr' '.mnu' '.mp4'
 '.mrk' '.pdf' '.png' '.pod' '.pptx' '.rar' '.sig' '.time' '.tmp' '.txt'
 '.xlsm' '.xlsx' '.xml' '.zip']

In [14]:
df = informacoes_df
df

,caminho,arquivo,tipo_arquivo,tipo_proj,data_criacao,tempo_acesso,tempo_modificacao,tempo_mudanca,tamanho,tamanho_kb
2952,P:\PROJETOS\07. ARACRUZ\02. Topografia\00. MAR...,Property,,Não definido,17/12/2024 11:12,17/12/2024 11:12,26/09/2024 13:03,17/12/2024 11:12,64532,63.02
4026,P:\PROJETOS\Notas\TBN2CAD\TBN2CAD.INI,TBN2CAD,.INI,Não definido,09/01/2025 12:47,09/01/2025 12:47,19/01/2024 15:13,09/01/2025 12:47,1565,1.53
1350,P:\PROJETOS\03. VILA VELHA\00. Existentes\Cont...,Contagem derivação 3 (68 ligações),.JPG,Não definido,17/12/2024 10:32,17/12/2024 10:32,24/02/2024 12:53,17/12/2024 10:32,256902,250.88
1388,P:\PROJETOS\03. VILA VELHA\Cadastro Existente\...,Contagem derivação 3 (68 ligações),.JPG,Não definido,09/01/2025 10:56,09/01/2025 10:56,24/02/2024 12:53,09/01/2025 10:56,256902,250.88
1389,P:\PROJETOS\03. VILA VELHA\Cadastro Existente\...,Contagem derivação 4 (3 ligações),.JPG,Não definido,09/01/2025 10:56,09/01/2025 10:56,24/02/2024 12:53,09/01/2025 10:56,122927,120.05
...,...,...,...,...,...,...,...,...,...,...
1998,P:\PROJETOS\04. GUARAPARI\12. ROD JONES SANTOS...,MODELO PROJETO,.zip,Não definido,17/12/2024 11:00,17/12/2024 11:00,26/09/2024 14:39,17/12/2024 11:00,896116,875.11
1496,P:\PROJETOS\03. VILA VELHA\Plano de Furo\Conve...,Conversa do WhatsApp com Patrick - Plano De Furo,.zip,Não definido,09/01/2025 11:02,09/01/2025 11:02,30/12/2024 13:55,09/01/2025 11:02,2763,2.70
2013,P:\PROJETOS\04. GUARAPARI\12. ROD JONES SANTOS...,MODELO PROJETO,.zip,Não definido,17/12/2024 11:01,17/12/2024 11:01,26/09/2024 14:39,17/12/2024 11:01,896116,875.11
486,P:\PROJETOS\02. VITÓRIA\02. MARUÍPE\_OLD\ATUAL...,VITÓRIA - REDE - AV. MARUÍPE,.zip,REDE,17/12/2024 09:59,17/12/2024 09:59,13/03/2024 14:02,17/12/2024 09:59,3443133,3362.43
0,P:\PROJETOS\21218301.zip,21218301,.zip,Não definido,09/01/2025 12:48,09/01/2025 12:48,17/12/2024 10:27,09/01/2025 12:48,1514622640,1479123.67

In [15]:
df.to_excel('tmp/projetos_origem.xlsx', index=False)

In [16]:
import os
import pandas as pd
import shutil
from tqdm import tqdm

def copiar_diferenca_csvs(csv_todos, csv_ja_copiados, extensoes_permitidas, pasta_destino, pasta_base):
    # Carrega os dois CSVs
    df_todos = pd.read_csv(csv_todos)
    df_ja_copiados = pd.read_csv(csv_ja_copiados)

    # Normaliza extensões e filtra os arquivos com extensões permitidas
    extensoes_permitidas = [ext.lower() for ext in extensoes_permitidas]
    #df_todos = df_todos[df_todos['tipo_arquivo'].str.lower().isin(extensoes_permitidas)]
    
    # Encontra a diferença entre os arquivos
    df_diferenca = pd.merge(
        df_todos,
        df_ja_copiados,
        on='caminho',
        how='left',
        indicator=True
    ).query('_merge == "left_only"').drop(columns=['_merge'])

    # Ordena por caminho e tamanho_kb_x
    df_diferenca = df_diferenca.sort_values(by=['tamanho_kb_x', 'caminho'], ascending=[True, True]).reset_index()
    df_diferenca = df_diferenca[4004:]
    display(df_diferenca)

    # Inicializa o progresso com tqdm
    with tqdm(total=len(df_diferenca), desc="Copiando arquivos", unit="arquivo") as pbar:
        for _, linha in df_diferenca.iterrows():
            caminho_origem = linha['caminho']
            tamanho_kb_x = linha['tamanho_kb_x']

            # Atualiza o tqdm com o nome do arquivo atual e tamanho
            pbar.set_postfix({"Arquivo Atual": os.path.basename(caminho_origem), "Tamanho (KB)": tamanho_kb_x})

            # Extrai o caminho relativo após "PROJETOS"
            if pasta_base in caminho_origem:
                caminho_relativo = caminho_origem.split(pasta_base, 1)[-1].lstrip("\\/")
                caminho_destino = os.path.join(pasta_destino, caminho_relativo)

                # Cria os diretórios necessários na pasta de destino
                os.makedirs(os.path.dirname(caminho_destino), exist_ok=True)

                try:
                    # Copia o arquivo
                    shutil.copy2(caminho_origem, caminho_destino)
                    pbar.update(1)  # Atualiza o progresso
                except Exception as e:
                    print(f"Erro ao copiar o arquivo {caminho_origem}: {e}")
                    pbar.update(1)  # Ainda assim, atualiza o progresso


# Configurações
csv_todos = r"database\list files\2025-01-22\2025-01-22_23.12.40 - CESAN 2025 BACKUP.csv"
csv_ja_copiados = r"database\list files\2025-01-27\2025-01-27_00.13.26 - CESAN 2025.csv"
extensoes_permitidas = ['.dwg', '.pdf', '.xlsx', '.xlsm', '.png', '.jpg', '.kml', '.kmz', '.txt', '.jxl']
pasta_destino = r"P:\PROJETOS"
pasta_base = "PROJETOS"  # Define o ponto base para a estrutura

# Executa a cópia
copiar_diferenca_csvs(csv_todos, csv_ja_copiados, extensoes_permitidas, pasta_destino, pasta_base)

SyntaxError: 'break' outside loop (3567714628.py, line 5)