In [10]:
import os
from datetime import datetime
import pandas as pd
import shutil
import subprocess

In [11]:
df = pd.read_excel('tmp/projetos_origem.xlsx')
df = df[df['tipo_arquivo']=='.dwg']
filtro = ~df['caminho'].str.contains('OLD|NOTAS|Notas|ANTIGOS|Antigos', regex=True)
df = df[filtro]
#filtro = df['caminho'].str.contains('CAD|REDE|MAP|PREF|TOP|BUILT', regex=True)
#filtro = df['caminho'].str.contains('Furo', regex=True)
df = df[filtro]
df = df.reset_index().drop(columns=['index'])
df

C:\Users\lucas.almeida\AppData\Local\Temp\ipykernel_28300\2664374682.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[filtro]

,caminho,arquivo,tipo_arquivo,tipo_proj,data_criacao,tempo_acesso,tempo_modificacao,tempo_mudanca,tamanho,tamanho_kb
0,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-REDE-VILA VELHA-R11.1,.dwg,REDE,22/01/2025 10:55,22/01/2025 10:55,16/01/2025 16:13,22/01/2025 10:55,3303442,3226.02
1,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-MAP-2024-10-21-RETA DA PENHA-R05,.dwg,MAP,22/01/2025 10:55,22/01/2025 10:55,22/10/2024 09:20,22/01/2025 10:55,4126230,4029.52
2,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-MAP-2024-10-21-RETA DA PENHA-R04,.dwg,MAP,22/01/2025 10:55,22/01/2025 10:55,22/10/2024 08:26,22/01/2025 10:55,4073518,3978.04
3,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-MAP-2024-10-21-PRAIA DO CANTO-R04,.dwg,MAP,22/01/2025 10:55,22/01/2025 10:55,31/10/2024 18:01,22/01/2025 10:55,3833328,3743.48
4,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,Capuaba MND,.dwg,Não definido,22/01/2025 10:55,22/01/2025 10:55,09/09/2024 10:04,22/01/2025 10:55,244285,238.56
...,...,...,...,...,...,...,...,...,...,...
384,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-LOC-ROD JONES DOS SANTOS NEVES-R03,.dwg,Não definido,22/01/2025 10:56,22/01/2025 10:56,30/10/2024 09:33,22/01/2025 10:56,2137465,2087.37
385,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-REDE-AV. LEITÃO DA SILVA-R02,.dwg,REDE,22/01/2025 10:55,22/01/2025 10:55,05/12/2024 08:11,22/01/2025 10:55,3761786,3673.62
386,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-REDE-AV. LEITÃO DA SILVA-R03 (CAMPO),.dwg,REDE,22/01/2025 10:55,22/01/2025 10:55,06/12/2024 11:04,22/01/2025 10:55,3163907,3089.75
387,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,2024-12-12 CL Vila Velha_ESTACAS,.dwg,Não definido,22/01/2025 10:56,22/01/2025 10:56,16/12/2024 09:37,22/01/2025 10:56,219543,214.40
388,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-ASF-BM02-LEITÃO DA SILVA-R03,.dwg,Não definido,22/01/2025 10:56,22/01/2025 10:56,01/11/2024 14:29,22/01/2025 10:56,671705,655.96

In [12]:
# Converter a coluna para datetime (caso necessário)
df['tempo_modificacao'] = pd.to_datetime(df['tempo_modificacao'], format='%d/%m/%Y %H:%M')

# Definir a data de corte
data_corte = pd.to_datetime('03/01/2024 00:00', format='%d/%m/%Y %H:%M')

# Filtrar para datas maiores que o corte
df = df[df['tempo_modificacao'] > data_corte]
df

,caminho,arquivo,tipo_arquivo,tipo_proj,data_criacao,tempo_acesso,tempo_modificacao,tempo_mudanca,tamanho,tamanho_kb
0,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-REDE-VILA VELHA-R11.1,.dwg,REDE,22/01/2025 10:55,22/01/2025 10:55,2025-01-16 16:13:00,22/01/2025 10:55,3303442,3226.02
1,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-MAP-2024-10-21-RETA DA PENHA-R05,.dwg,MAP,22/01/2025 10:55,22/01/2025 10:55,2024-10-22 09:20:00,22/01/2025 10:55,4126230,4029.52
2,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-MAP-2024-10-21-RETA DA PENHA-R04,.dwg,MAP,22/01/2025 10:55,22/01/2025 10:55,2024-10-22 08:26:00,22/01/2025 10:55,4073518,3978.04
3,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-MAP-2024-10-21-PRAIA DO CANTO-R04,.dwg,MAP,22/01/2025 10:55,22/01/2025 10:55,2024-10-31 18:01:00,22/01/2025 10:55,3833328,3743.48
4,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,Capuaba MND,.dwg,Não definido,22/01/2025 10:55,22/01/2025 10:55,2024-09-09 10:04:00,22/01/2025 10:55,244285,238.56
...,...,...,...,...,...,...,...,...,...,...
384,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-LOC-ROD JONES DOS SANTOS NEVES-R03,.dwg,Não definido,22/01/2025 10:56,22/01/2025 10:56,2024-10-30 09:33:00,22/01/2025 10:56,2137465,2087.37
385,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-REDE-AV. LEITÃO DA SILVA-R02,.dwg,REDE,22/01/2025 10:55,22/01/2025 10:55,2024-12-05 08:11:00,22/01/2025 10:55,3761786,3673.62
386,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-REDE-AV. LEITÃO DA SILVA-R03 (CAMPO),.dwg,REDE,22/01/2025 10:55,22/01/2025 10:55,2024-12-06 11:04:00,22/01/2025 10:55,3163907,3089.75
387,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,2024-12-12 CL Vila Velha_ESTACAS,.dwg,Não definido,22/01/2025 10:56,22/01/2025 10:56,2024-12-16 09:37:00,22/01/2025 10:56,219543,214.40
388,C:\Users\lucas.almeida\OneDrive - Sanit\10002 ...,VIT-ASF-BM02-LEITÃO DA SILVA-R03,.dwg,Não definido,22/01/2025 10:56,22/01/2025 10:56,2024-11-01 14:29:00,22/01/2025 10:56,671705,655.96

In [13]:
def copiar_arquivos_para_temp(df, column, input_base, tmp_folder):
    """Copia os arquivos DWG específicos para uma pasta temporária, mantendo a estrutura."""
    arquivos_copiados = []

    for dwg_file in df[column]:
        if os.path.isfile(dwg_file) and dwg_file.lower().endswith(".dwg"):
            caminho_relativo = os.path.relpath(dwg_file, input_base)
            caminho_temp = os.path.join(tmp_folder, caminho_relativo)

            # Cria subpastas necessárias
            os.makedirs(os.path.dirname(caminho_temp), exist_ok=True)

            # Copia o arquivo para a pasta temporária
            shutil.copy(dwg_file, caminho_temp)
            arquivos_copiados.append(caminho_temp)
        else:
            print(f"Arquivo não encontrado ou inválido: {dwg_file}")
    
    return arquivos_copiados

In [14]:
def convert_dwg_to_dxf(input_folder, output_folder):
    converter_path = r"C:\\Program Files\\ODA\\ODAFileConverter 25.8.0\\ODAFileConverter.exe"

    command = [
        converter_path,
        input_folder,
        output_folder,
        "ACAD2018",  # Versão de saída
        "DXF",  # Tipo de saída
        "1",  # Auditar cada arquivo
        "1"  # Recursivo (subpastas)
    ]

    try:
        print(f"Executando: {' '.join(command)}")
        subprocess.run(command, shell=True, check=True)
        print("Conversão concluída com sucesso!")
    except subprocess.CalledProcessError as e:
        print(f"Erro durante a conversão: {e}")

# Exemplo de uso
#convert_dwg_to_dxf(
#    r"C:\\Users\\lucas.almeida\\OneDrive - Sanit\\CESAN\\PROJETOS\\02. VITÓRIA\\01. LEITÃO DA SILVA",
#    r"C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects"
#)

In [15]:
def listar_arquivos(folder):
    """Lista todos os arquivos DXF na pasta orária e suas subpastas."""
    arquivos = []
    for root, _, files in os.walk(folder):
        for file in files:
            if file.lower().endswith(".dxf"):
                arquivos.append(os.path.join(root, file))
    return arquivos

In [16]:
def mover_arquivos(folder_origin, folder_detiny):
    """Move os arquivos convertidos da pasta temp/dxf para a estrutura correta na pasta de saída."""
    arquivos = listar_arquivos(folder_origin)
    for caminho in arquivos:
        caminho_relativo = os.path.relpath(caminho, folder_origin)
        print(caminho_relativo)
        caminho_destino = os.path.join(folder_detiny, caminho_relativo)
        print(caminho_destino)

        # Cria as subpastas necessárias no caminho de destino, caso não existam
        os.makedirs(os.path.dirname(caminho_destino), exist_ok=True)

        # Substitui o arquivo antigo pelo novo no local de destino
        if os.path.exists(caminho_destino):
            os.remove(caminho_destino)  # Remove o antigo para evitar erro de substituição
        shutil.move(caminho, caminho_destino)  # Move o novo arquivo

        print(f"Arquivo {caminho} movido para {caminho_destino}")

In [17]:
def remover_pasta_temp(tmp_folder):
    """Remove a pasta temporária e seus conteúdos."""
    shutil.rmtree(tmp_folder, ignore_errors=True)
    print("Pasta temporária removida.")

In [18]:
tmp_folder_input = "tmp\\dwg"
tmp_folder_output = "tmp\\dxf"
os.makedirs(tmp_folder_input, exist_ok=True)
os.makedirs(tmp_folder_output, exist_ok=True)

folder_input = 'C:\\Users\\lucas.almeida\\OneDrive - Sanit\\10002 - CENSAN PLANEJAMENTO\\PROJETOS'
arquivos_copiados = copiar_arquivos_para_temp(df, 'caminho', folder_input, tmp_folder_input)

convert_dwg_to_dxf(tmp_folder_input, tmp_folder_output)

folder_output = 'database\\projects\\CESAN 2025'
mover_arquivos(tmp_folder_output, folder_output)

shutil.rmtree(tmp_folder_input, ignore_errors=True)
shutil.rmtree(tmp_folder_output, ignore_errors=True)

Executando: C:\\Program Files\\ODA\\ODAFileConverter 25.8.0\\ODAFileConverter.exe tmp\dwg tmp\dxf ACAD2018 DXF 1 1
Conversão concluída com sucesso!
00. RECEBIDOS\Cadastro_Drenagem_PMV_Av_Maruipe_Vitoria.dxf
database\projects\CESAN 2025\00. RECEBIDOS\Cadastro_Drenagem_PMV_Av_Maruipe_Vitoria.dxf
Arquivo tmp\dxf\00. RECEBIDOS\Cadastro_Drenagem_PMV_Av_Maruipe_Vitoria.dxf movido para database\projects\CESAN 2025\00. RECEBIDOS\Cadastro_Drenagem_PMV_Av_Maruipe_Vitoria.dxf
00. RECEBIDOS\Mapa de Vila Velha2 (2) - Copia.dxf
database\projects\CESAN 2025\00. RECEBIDOS\Mapa de Vila Velha2 (2) - Copia.dxf
Arquivo tmp\dxf\00. RECEBIDOS\Mapa de Vila Velha2 (2) - Copia.dxf movido para database\projects\CESAN 2025\00. RECEBIDOS\Mapa de Vila Velha2 (2) - Copia.dxf
00. RECEBIDOS\Planta Geral Municipio de Vila Velha.dxf
database\projects\CESAN 2025\00. RECEBIDOS\Planta Geral Municipio de Vila Velha.dxf
Arquivo tmp\dxf\00. RECEBIDOS\Planta Geral Municipio de Vila Velha.dxf movido para database\projects\CESAN 2025\00. RECEBIDOS\Planta Geral Municipio de Vila Velha.dxf
00. RECEBIDOS\Planta Geral Municipio de Vitória.dxf
database\projects\CESAN 2025\00. RECEBIDOS\Planta Geral Municipio de Vitória.dxf
Arquivo tmp\dxf\00. RECEBIDOS\Planta Geral Municipio de Vitória.dxf movido para database\projects\CESAN 2025\00. RECEBIDOS\Planta Geral Municipio de Vitória.dxf
00. RECEBIDOS\01. Vitória\O-DVT_A.dxf
database\projects\CESAN 2025\00. RECEBIDOS\01. Vitória\O-DVT_A.dxf
Arquivo tmp\dxf\00. RECEBIDOS\01. Vitória\O-DVT_A.dxf movido para database\projects\CESAN 2025\00. RECEBIDOS\01. Vitória\O-DVT_A.dxf
00. RECEBIDOS\01. Vitória\O-DVT_E.dxf
database\projects\CESAN 2025\00. RECEBIDOS\01. Vitória\O-DVT_E.dxf
Arquivo tmp\dxf\00. RECEBIDOS\01. Vitória\O-DVT_E.dxf movido para database\projects\CESAN 2025\00. RECEBIDOS\01. Vitória\O-DVT_E.dxf
00. RECEBIDOS\01. Vitória\redes Vitória demanda Praia do Canto.dxf
database\projects\CESAN 2025\00. RECEBIDOS\01. Vitória\redes Vitória demanda Praia do Canto.dxf
Arquivo tmp\dxf\00. RECEBIDOS\01. Vitória\redes Vitória demanda Praia do Canto.dxf movido para database\projects\CESAN 2025\00. RECEBIDOS\01. Vitória\redes Vitória demanda Praia do Canto.dxf
00. RECEBIDOS\01. Vitória\Vitória Operacional_Água.dxf
database\projects\CESAN 2025\00. RECEBIDOS\01. Vitória\Vitória Operacional_Água.dxf
Arquivo tmp\dxf\00. RECEBIDOS\01. Vitória\Vitória Operacional_Água.dxf movido para database\projects\CESAN 2025\00. RECEBIDOS\01. Vitória\Vitória Operacional_Água.dxf
00. RECEBIDOS\01. Vitória\08. JOÃO DOS SANTOS FILHO\JOÃO DOS SANTOS FILHO.dxf
database\projects\CESAN 2025\00. RECEBIDOS\01. Vitória\08. JOÃO DOS SANTOS FILHO\JOÃO DOS SANTOS FILHO.dxf
Arquivo tmp\dxf\00. RECEBIDOS\01. Vitória\08. JOÃO DOS SANTOS FILHO\JOÃO DOS SANTOS FILHO.dxf movido para database\projects\CESAN 2025\00. RECEBIDOS\01. Vitória\08. JOÃO DOS SANTOS FILHO\JOÃO DOS SANTOS FILHO.dxf
00. RECEBIDOS\02. Guarapari\Guarapari_Esgoto.dxf
database\projects\CESAN 2025\00. RECEBIDOS\02. Guarapari\Guarapari_Esgoto.dxf
Arquivo tmp\dxf\00. RECEBIDOS\02. Guarapari\Guarapari_Esgoto.dxf movido para database\projects\CESAN 2025\00. RECEBIDOS\02. Guarapari\Guarapari_Esgoto.dxf
00. RECEBIDOS\02. Guarapari\O-DLT_A-_GUARAPARI[1].dxf
database\projects\CESAN 2025\00. RECEBIDOS\02. Guarapari\O-DLT_A-_GUARAPARI[1].dxf
Arquivo tmp\dxf\00. RECEBIDOS\02. Guarapari\O-DLT_A-_GUARAPARI[1].dxf movido para database\projects\CESAN 2025\00. RECEBIDOS\02. Guarapari\O-DLT_A-_GUARAPARI[1].dxf
00. RECEBIDOS\03. Serra\TRAVESSIA DN600 SERRA.dxf
database\projects\CESAN 2025\00. RECEBIDOS\03. Serra\TRAVESSIA DN600 SERRA.dxf
Arquivo tmp\dxf\00. RECEBIDOS\03. Serra\TRAVESSIA DN600 SERRA.dxf movido para database\projects\CESAN 2025\00. RECEBIDOS\03. Serra\TRAVESSIA DN600 SERRA.dxf
00. RECEBIDOS\13. Aracruz\DVT_A-ARACRUZ.dxf
database\projects\CESAN 2025\00. RECEBIDOS\13. Aracruz\DVT_A-ARACRUZ.dxf
Arquivo tmp\dxf\00. RECEBIDOS\13. Aracruz\DVT_A-ARACRUZ.dxf movido para database\projects\CESAN 2025\00. RECEBIDOS\13. Aracruz\DVT_A-ARACRUZ.dxf
01. CANTEIRO\01. Serra - R. Florianópolis\VIT-ARQ-CANTEIRO 01-R00.dxf
database\projects\CESAN 2025\01. CANTEIRO\01. Serra - R. Florianópolis\VIT-ARQ-CANTEIRO 01-R00.dxf
Arquivo tmp\dxf\01. CANTEIRO\01. Serra - R. Florianópolis\VIT-ARQ-CANTEIRO 01-R00.dxf movido para database\projects\CESAN 2025\01. CANTEIRO\01. Serra - R. Florianópolis\VIT-ARQ-CANTEIRO 01-R00.dxf
01. CANTEIRO\01. Serra - R. Florianópolis\VIT-ARQ-CANTEIRO SERRA-R00.dxf
database\projects\CESAN 2025\01. CANTEIRO\01. Serra - R. Florianópolis\VIT-ARQ-CANTEIRO SERRA-R00.dxf
Arquivo tmp\dxf\01. CANTEIRO\01. Serra - R. Florianópolis\VIT-ARQ-CANTEIRO SERRA-R00.dxf movido para database\projects\CESAN 2025\01. CANTEIRO\01. Serra - R. Florianópolis\VIT-ARQ-CANTEIRO SERRA-R00.dxf
01. CANTEIRO\02. Serra - Av. Porto Dourado\VIT-ARQ-CANTEIRO 02-R00.dxf
database\projects\CESAN 2025\01. CANTEIRO\02. Serra - Av. Porto Dourado\VIT-ARQ-CANTEIRO 02-R00.dxf
Arquivo tmp\dxf\01. CANTEIRO\02. Serra - Av. Porto Dourado\VIT-ARQ-CANTEIRO 02-R00.dxf movido para database\projects\CESAN 2025\01. CANTEIRO\02. Serra - Av. Porto Dourado\VIT-ARQ-CANTEIRO 02-R00.dxf
01. CANTEIRO\03. Serra - Rua Braulina Baptista Lopes\VIT-ARQ-CANTEIRO 03-R00.dxf
database\projects\CESAN 2025\01. CANTEIRO\03. Serra - Rua Braulina Baptista Lopes\VIT-ARQ-CANTEIRO 03-R00.dxf
Arquivo tmp\dxf\01. CANTEIRO\03. Serra - Rua Braulina Baptista Lopes\VIT-ARQ-CANTEIRO 03-R00.dxf movido para database\projects\CESAN 2025\01. CANTEIRO\03. Serra - Rua Braulina Baptista Lopes\VIT-ARQ-CANTEIRO 03-R00.dxf
01. CANTEIRO\03. Serra - Rua Braulina Baptista Lopes\VIT-ARQ-CANTEIRO 03-R01.dxf
database\projects\CESAN 2025\01. CANTEIRO\03. Serra - Rua Braulina Baptista Lopes\VIT-ARQ-CANTEIRO 03-R01.dxf
Arquivo tmp\dxf\01. CANTEIRO\03. Serra - Rua Braulina Baptista Lopes\VIT-ARQ-CANTEIRO 03-R01.dxf movido para database\projects\CESAN 2025\01. CANTEIRO\03. Serra - Rua Braulina Baptista Lopes\VIT-ARQ-CANTEIRO 03-R01.dxf
01. CANTEIRO\ESCRITÓRIO - ENSEADA DO SUÁ\LAYOUT.dxf
database\projects\CESAN 2025\01. CANTEIRO\ESCRITÓRIO - ENSEADA DO SUÁ\LAYOUT.dxf
Arquivo tmp\dxf\01. CANTEIRO\ESCRITÓRIO - ENSEADA DO SUÁ\LAYOUT.dxf movido para database\projects\CESAN 2025\01. CANTEIRO\ESCRITÓRIO - ENSEADA DO SUÁ\LAYOUT.dxf
02. VITÓRIA\VIT-REDE-VITÓRIA-R00.dxf
database\projects\CESAN 2025\02. VITÓRIA\VIT-REDE-VITÓRIA-R00.dxf
Arquivo tmp\dxf\02. VITÓRIA\VIT-REDE-VITÓRIA-R00.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\VIT-REDE-VITÓRIA-R00.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-04-26 AV. LEITÃO DA SILVA.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-04-26 AV. LEITÃO DA SILVA.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-04-26 AV. LEITÃO DA SILVA.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-04-26 AV. LEITÃO DA SILVA.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-04-30 SOND LEITÃO DA SILVA.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-04-30 SOND LEITÃO DA SILVA.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-04-30 SOND LEITÃO DA SILVA.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-04-30 SOND LEITÃO DA SILVA.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-06 SOND LEITÃO DA SILVA.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-06 SOND LEITÃO DA SILVA.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-06 SOND LEITÃO DA SILVA.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-06 SOND LEITÃO DA SILVA.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-07 AV. LEITÃO DA SILVA.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-07 AV. LEITÃO DA SILVA.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-07 AV. LEITÃO DA SILVA.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-07 AV. LEITÃO DA SILVA.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-07 SOND AV. LEITÃO DA SILVA.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-07 SOND AV. LEITÃO DA SILVA.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-07 SOND AV. LEITÃO DA SILVA.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-07 SOND AV. LEITÃO DA SILVA.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-08 SOND AV. LEITÃO DA SILVA.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-08 SOND AV. LEITÃO DA SILVA.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-08 SOND AV. LEITÃO DA SILVA.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-08 SOND AV. LEITÃO DA SILVA.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-28 AV. LEITÃO DA SILVA.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-28 AV. LEITÃO DA SILVA.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-28 AV. LEITÃO DA SILVA.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-05-28 AV. LEITÃO DA SILVA.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-07-06 AV. LEITÃO DA SILVA.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-07-06 AV. LEITÃO DA SILVA.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-07-06 AV. LEITÃO DA SILVA.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia\VIT-TOP-2024-07-06 AV. LEITÃO DA SILVA.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\03. Cadastros Existentes\VIT-CAD GERAL-AV. LEITÃO DA SILVA-R00.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\03. Cadastros Existentes\VIT-CAD GERAL-AV. LEITÃO DA SILVA-R00.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\03. Cadastros Existentes\VIT-CAD GERAL-AV. LEITÃO DA SILVA-R00.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\03. Cadastros Existentes\VIT-CAD GERAL-AV. LEITÃO DA SILVA-R00.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\VIT-REDE-AV. LEITÃO DA SILVA-R05.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\VIT-REDE-AV. LEITÃO DA SILVA-R05.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\VIT-REDE-AV. LEITÃO DA SILVA-R05.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\VIT-REDE-AV. LEITÃO DA SILVA-R05.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\01. Estudo\VIT-REDE-AV. LEITÃO DA SILVA-R00.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\01. Estudo\VIT-REDE-AV. LEITÃO DA SILVA-R00.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\01. Estudo\VIT-REDE-AV. LEITÃO DA SILVA-R00.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\01. Estudo\VIT-REDE-AV. LEITÃO DA SILVA-R00.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R00\VIT-CIPP-AV. LEITÃO DA SILVA-R00.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R00\VIT-CIPP-AV. LEITÃO DA SILVA-R00.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R00\VIT-CIPP-AV. LEITÃO DA SILVA-R00.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R00\VIT-CIPP-AV. LEITÃO DA SILVA-R00.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R01\VIT-REDE-AV. LEITÃO DA SILVA-R01.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R01\VIT-REDE-AV. LEITÃO DA SILVA-R01.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R01\VIT-REDE-AV. LEITÃO DA SILVA-R01.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R01\VIT-REDE-AV. LEITÃO DA SILVA-R01.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R02\VIT-REDE-AV. LEITÃO DA SILVA-R02.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R02\VIT-REDE-AV. LEITÃO DA SILVA-R02.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R02\VIT-REDE-AV. LEITÃO DA SILVA-R02.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R02\VIT-REDE-AV. LEITÃO DA SILVA-R02.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R03\VIT-REDE-AV. LEITÃO DA SILVA-R03 (CAMPO).dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R03\VIT-REDE-AV. LEITÃO DA SILVA-R03 (CAMPO).dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R03\VIT-REDE-AV. LEITÃO DA SILVA-R03 (CAMPO).dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R03\VIT-REDE-AV. LEITÃO DA SILVA-R03 (CAMPO).dxf
02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R03\VIT-REDE-AV. LEITÃO DA SILVA-R03.0.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R03\VIT-REDE-AV. LEITÃO DA SILVA-R03.0.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R03\VIT-REDE-AV. LEITÃO DA SILVA-R03.0.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R03\VIT-REDE-AV. LEITÃO DA SILVA-R03.0.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R03\VIT-REDE-AV. LEITÃO DA SILVA-R04.1.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R03\VIT-REDE-AV. LEITÃO DA SILVA-R04.1.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R03\VIT-REDE-AV. LEITÃO DA SILVA-R04.1.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R03\VIT-REDE-AV. LEITÃO DA SILVA-R04.1.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R04\VIT-REDE-AV. LEITÃO DA SILVA-R04.0.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R04\VIT-REDE-AV. LEITÃO DA SILVA-R04.0.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R04\VIT-REDE-AV. LEITÃO DA SILVA-R04.0.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\R04\VIT-REDE-AV. LEITÃO DA SILVA-R04.0.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\07. Prefeitura\VIT-PREF-AV. LEITÃO DA SILVA-R00.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\07. Prefeitura\VIT-PREF-AV. LEITÃO DA SILVA-R00.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\07. Prefeitura\VIT-PREF-AV. LEITÃO DA SILVA-R00.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\07. Prefeitura\VIT-PREF-AV. LEITÃO DA SILVA-R00.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\07. Prefeitura\FOTOS\VIT-FOTOS-AV. LEITÃO DA SILVA-R00.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\07. Prefeitura\FOTOS\VIT-FOTOS-AV. LEITÃO DA SILVA-R00.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\07. Prefeitura\FOTOS\VIT-FOTOS-AV. LEITÃO DA SILVA-R00.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\07. Prefeitura\FOTOS\VIT-FOTOS-AV. LEITÃO DA SILVA-R00.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-04-22\VIT-MAP-AV. LEITÃO DA SILVA-R01.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-04-22\VIT-MAP-AV. LEITÃO DA SILVA-R01.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-04-22\VIT-MAP-AV. LEITÃO DA SILVA-R01.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-04-22\VIT-MAP-AV. LEITÃO DA SILVA-R01.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-05-17\VIT-MAP-2024-05-17-AV. LEITÃO DA SILVA-R02.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-05-17\VIT-MAP-2024-05-17-AV. LEITÃO DA SILVA-R02.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-05-17\VIT-MAP-2024-05-17-AV. LEITÃO DA SILVA-R02.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-05-17\VIT-MAP-2024-05-17-AV. LEITÃO DA SILVA-R02.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-05-17\VIT-MAP-AV. LEITÃO DA SILVA-R02.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-05-17\VIT-MAP-AV. LEITÃO DA SILVA-R02.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-05-17\VIT-MAP-AV. LEITÃO DA SILVA-R02.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-05-17\VIT-MAP-AV. LEITÃO DA SILVA-R02.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-06-15\VIT-MAP-2024-06-15-AV. LEITÃO DA SILVA-R03.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-06-15\VIT-MAP-2024-06-15-AV. LEITÃO DA SILVA-R03.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-06-15\VIT-MAP-2024-06-15-AV. LEITÃO DA SILVA-R03.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-06-15\VIT-MAP-2024-06-15-AV. LEITÃO DA SILVA-R03.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-07-29\VIT-MAP-2024-07-29-AV. LEITÃO DA SILVA-R03.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-07-29\VIT-MAP-2024-07-29-AV. LEITÃO DA SILVA-R03.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-07-29\VIT-MAP-2024-07-29-AV. LEITÃO DA SILVA-R03.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-07-29\VIT-MAP-2024-07-29-AV. LEITÃO DA SILVA-R03.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\11. Cadastro Final\VIT-CAD-AV. LEITÃO DA SILVA-R01.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\11. Cadastro Final\VIT-CAD-AV. LEITÃO DA SILVA-R01.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\11. Cadastro Final\VIT-CAD-AV. LEITÃO DA SILVA-R01.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\11. Cadastro Final\VIT-CAD-AV. LEITÃO DA SILVA-R01.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\CAIXAS CIRCULARES\rev\VIT-EST-VALA 1-ARMAÇÃO-R00-CIRCULAR.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\CAIXAS CIRCULARES\rev\VIT-EST-VALA 1-ARMAÇÃO-R00-CIRCULAR.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\CAIXAS CIRCULARES\rev\VIT-EST-VALA 1-ARMAÇÃO-R00-CIRCULAR.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\CAIXAS CIRCULARES\rev\VIT-EST-VALA 1-ARMAÇÃO-R00-CIRCULAR.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\CAIXAS CIRCULARES\rev\VIT-EST-VALA 1-FORMAS-R00-CIRCULAR.dxf
database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\CAIXAS CIRCULARES\rev\VIT-EST-VALA 1-FORMAS-R00-CIRCULAR.dxf
Arquivo tmp\dxf\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\CAIXAS CIRCULARES\rev\VIT-EST-VALA 1-FORMAS-R00-CIRCULAR.dxf movido para database\projects\CESAN 2025\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\CAIXAS CIRCULARES\rev\VIT-EST-VALA 1-FORMAS-R00-CIRCULAR.dxf
02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\CAIXAS CIRCULARES\rev\VIT-EST-VALA 2-ARMAÇÃO-R00-CIRCULAR.dxf

In [19]:
def deletar_pastas_vazias(diretorio_raiz):
    # Percorre a estrutura de diretórios de baixo para cima (bottom-up)
    for root, dirs, files in os.walk(diretorio_raiz, topdown=False):
        for dir_name in dirs:
            caminho_completo = os.path.join(root, dir_name)

            # Tenta remover a pasta, se estiver vazia
            try:
                os.rmdir(caminho_completo)
                print(f"Pasta vazia deletada: {caminho_completo}")
            except OSError as e:
                # Se não puder deletar, provavelmente não está vazia
                print(f"Erro ao deletar {caminho_completo}: {e}")

# Exemplo de uso
diretorio = r"C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects"  # Substituir pelo caminho desejado
deletar_pastas_vazias(diretorio)

Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\00. RECEBIDOS\01. Vitória\06. SERAFIM DERENZE\00. Planilhas: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\00. RECEBIDOS\\01. Vitória\\06. SERAFIM DERENZE\\00. Planilhas'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\00. RECEBIDOS\01. Vitória\08. JOÃO DOS SANTOS FILHO\00. Planilhas: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\00. RECEBIDOS\\01. Vitória\\08. JOÃO DOS SANTOS FILHO\\00. Planilhas'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\00. RECEBIDOS\01. Vitória\06. SERAFIM DERENZE: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\00. RECEBIDOS\\01. Vitória\\06. SERAFIM DERENZE'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\00. RECEBIDOS\01. Vitória\08. JOÃO DOS SANTOS FILHO: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\00. RECEBIDOS\\01. Vitória\\08. JOÃO DOS SANTOS FILHO'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\00. RECEBIDOS\01. Vitória: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\00. RECEBIDOS\\01. Vitória'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\00. RECEBIDOS\02. Guarapari: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\00. RECEBIDOS\\02. Guarapari'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\00. RECEBIDOS\03. Serra: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\00. RECEBIDOS\\03. Serra'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\00. RECEBIDOS\13. Aracruz: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\00. RECEBIDOS\\13. Aracruz'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\OLD\R01 - 2024-04-23: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\OLD\\R01 - 2024-04-23'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar\OLD: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\OLD'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\07. Prefeitura\FOTOS: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\07. Prefeitura\\FOTOS'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-04-22: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-04-22'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-05-17: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-05-17'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-06-15: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-06-15'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado\MAP - 2024-07-29: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-07-29'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\valas circulares\rev: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\valas circulares\\rev'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\_OLD\R00-CAIXAS RETANGULARES\01. CAIXA 1\01. DWG: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\_OLD\\R00-CAIXAS RETANGULARES\\01. CAIXA 1\\01. DWG'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\_OLD\R00-CAIXAS RETANGULARES\01. CAIXA 1: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\_OLD\\R00-CAIXAS RETANGULARES\\01. CAIXA 1'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\_OLD\R00-CAIXAS RETANGULARES\02. CAIXA 2: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\_OLD\\R00-CAIXAS RETANGULARES\\02. CAIXA 2'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\_OLD\R00-CAIXAS RETANGULARES\03. CAIXA 3: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\_OLD\\R00-CAIXAS RETANGULARES\\03. CAIXA 3'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\_OLD\R00-CAIXAS RETANGULARES\04. CAIXA 4: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\_OLD\\R00-CAIXAS RETANGULARES\\04. CAIXA 4'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\_OLD\R00-CAIXAS RETANGULARES\05. CAIXA 5: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\_OLD\\R00-CAIXAS RETANGULARES\\05. CAIXA 5'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\_OLD\R01-CAIXA CILINDRICAS\CESAN - Caixas com seção circular: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\_OLD\\R01-CAIXA CILINDRICAS\\CESAN - Caixas com seção circular'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\_OLD\R01-CAIXA CILINDRICAS\Fwd_ CESAN - Caixas com seção circular: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\_OLD\\R01-CAIXA CILINDRICAS\\Fwd_ CESAN - Caixas com seção circular'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\_OLD\R00-CAIXAS RETANGULARES: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\_OLD\\R00-CAIXAS RETANGULARES'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\_OLD\R01-CAIXA CILINDRICAS: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\_OLD\\R01-CAIXA CILINDRICAS'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\valas circulares: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\valas circulares'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural\_OLD: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural\\_OLD'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\Nova pasta\PROJETO CAIXAS: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\Nova pasta\\PROJETO CAIXAS'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\_OLD\EXEC: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\_OLD\\EXEC'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\_OLD\TOPOGRAFIA: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\_OLD\\TOPOGRAFIA'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\_OLD\v1: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\_OLD\\v1'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\02. Topografia: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\03. Cadastros Existentes: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\03. Cadastros Existentes'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\06. Rede a Executar: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\07. Prefeitura: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\07. Prefeitura'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\10. Mapa Iluminado: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\11. Cadastro Final: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\11. Cadastro Final'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\12. Projeto Estrutural: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\12. Projeto Estrutural'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\13. Sinalização: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\13. Sinalização'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\Nova pasta: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\Nova pasta'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\01. LEITÃO DA SILVA\_OLD: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\_OLD'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\02. MARUÍPE\_OLD\ATUALIZADOS 13_03: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\02. MARUÍPE\\_OLD\\ATUALIZADOS 13_03'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\02. MARUÍPE\00. Planilhas: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\02. MARUÍPE\\00. Planilhas'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\02. MARUÍPE\01. Rede a Executar: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\02. MARUÍPE\\01. Rede a Executar'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\02. MARUÍPE\_OLD: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\02. MARUÍPE\\_OLD'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\03. PRAIA DO CANTO\02. Mapa Iluminado\BM07 - 16.09-15.10\RAMAIS: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\03. PRAIA DO CANTO\02. Mapa Iluminado\BM06 - 16.08-15.09: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM06 - 16.08-15.09'
Erro ao deletar C:\\Users\\lucas.almeida\\OneDrive - sanejet\\PROGRMAÇÃO\\KMZ TO XLSX\\database\\projects\10002-CESAN\02. VITÓRIA\03. PRAIA DO CANTO\02. Mapa Iluminado\BM07 - 16.09-15.10: [WinError 145] A pasta não está vazia: 'C:\\\\Users\\\\lucas.almeida\\\\OneDrive - sanejet\\\\PROGRMAÇÃO\\\\KMZ TO XLSX\\\\database\\\\projects\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10'