In [11]:
import os
from datetime import datetime
import pandas as pd
from tqdm import tqdm

tqdm.pandas()

In [12]:
import re

def categoria_proj(nome_arquivo):
    # Define os padrões e as categorias correspondentes
    categorias = {
        "REDE": r"\bREDE\b",
        "PREF": r"\bPREF\b",
        "MAP": r"\bMAP\b",
        "TOP": r"\bTOP\b",
        "CAD": r"\bCAD\b",
        "SPT": r"\bSPT\b",
        "AS BUILT": r"\bAS BUILT\b",
        "RAMAL": r"\bRAMAL\b",
        "PLANO DE FURO": r"\bPF\b"
    }
    
    # Verifica qual padrão corresponde ao nome do arquivo
    for categoria, padrao in categorias.items():
        if re.search(padrao, nome_arquivo):
            return categoria
    
    # Retorna "Não definido" caso não encontre uma categoria
    return "Não definido"

In [13]:
def obter_informacoes_arquivos(pasta):
    informacoes_arquivos = []

    for pasta_atual, sub_pastas, arquivos in tqdm(os.walk(pasta)):
        for arquivo in arquivos:
            caminho_completo = os.path.join(pasta_atual, arquivo)

            try:
                info = os.stat(caminho_completo)
            except (PermissionError, FileNotFoundError) as e:
                # Lidar com exceções (pular o arquivo e imprimir uma mensagem, se desejar)
                print(f"Erro ao obter informações de {caminho_completo}: {e}")
                continue

            # Extrair informações desejadas
            caminho_arquivo = caminho_completo
            arquivo, tipo_arquivo = os.path.splitext(arquivo)
            autor = info.st_uid
            data_criacao = datetime.fromtimestamp(info.st_ctime).strftime("%d/%m/%Y %H:%M")
            tempo_acesso = datetime.fromtimestamp(info.st_atime).strftime("%d/%m/%Y %H:%M")
            tempo_modificacao = datetime.fromtimestamp(info.st_mtime).strftime("%d/%m/%Y %H:%M")
            tempo_mudanca = datetime.fromtimestamp(info.st_ctime).strftime("%d/%m/%Y %H:%M")
            tamanho_arquivo = info.st_size,
            tipo_proj = categoria_proj(arquivo)

            # Criar um dicionário com as informações
            informacao_arquivo = {
                'caminho': caminho_arquivo,
                'arquivo': arquivo,
                'tipo_arquivo': tipo_arquivo,
                'tipo_proj': tipo_proj,
                'data_criacao': data_criacao,
                'tempo_acesso': tempo_acesso,
                'tempo_modificacao': tempo_modificacao,
                'tempo_mudanca': tempo_mudanca,
                'tamanho': tamanho_arquivo
            }

            # Adicionar à lista de informações
            informacoes_arquivos.append(informacao_arquivo)
    print(informacoes_arquivos)
    return informacoes_arquivos

In [14]:
def criar_pasta_do_dia(caminho_base, nome):
    # Obtém a data atual
    data_atual = datetime.now()

    # Formata a data como YYYYMMDD
    data = data_atual.strftime("%Y-%m-%d")
    data_hora = data_atual.strftime("%Y-%m-%d_%H.%M.%S")

    # Constrói o caminho da pasta do dia
    caminho_pasta_do_dia = os.path.join(caminho_base, data)

    # Cria a pasta se ela não existir
    if not os.path.exists(caminho_pasta_do_dia):
        os.makedirs(caminho_pasta_do_dia)

    # Constrói o nome do arquivo com a data
    nome_arquivo = f'{caminho_pasta_do_dia}\{data_hora} - {nome}.csv'

    # Salva o DataFrame no arquivo
    informacoes_df.to_csv(nome_arquivo, encoding="utf-8")

    return informacoes_df.to_csv(nome_arquivo, encoding="utf-8")

<string>:17: SyntaxWarning: invalid escape sequence '\{'
<>:17: SyntaxWarning: invalid escape sequence '\{'
<string>:17: SyntaxWarning: invalid escape sequence '\{'
<>:17: SyntaxWarning: invalid escape sequence '\{'
C:\Users\lucas.almeida\AppData\Local\Temp\ipykernel_3684\336270697.py:17: SyntaxWarning: invalid escape sequence '\{'
  nome_arquivo = f'{caminho_pasta_do_dia}\{data_hora} - {nome}.csv'

In [15]:
caminho = ['database\\projects data', 'database\\projects\\10002-CESAN-25']
nome = ['Projects Data', 'Projects 10002-CENSAN 25']

Pastas = {
  'nome': nome,
  'caminho': caminho
}

Pastas_df = pd.DataFrame(Pastas)

for index, row in tqdm(Pastas_df.iterrows()):

  informacoes = obter_informacoes_arquivos(row['caminho'])

  informacoes_df = pd.DataFrame(informacoes)
  informacoes_df['tamanho'] = informacoes_df['tamanho'].apply(lambda x: x[0] if isinstance(x, tuple) else x)

  informacoes_df['tamanho_kb'] = round(informacoes_df['tamanho']/1024, 2)

  display(informacoes_df)

  informacoes_df = informacoes_df.sort_values(by='tipo_arquivo')
  print(informacoes_df['tipo_arquivo'].unique())

  nome = row['nome']
  caminho_pasta_do_dia = criar_pasta_do_dia('.\\database\\list data', nome)

107it [00:00, 3255.57it/s]

[{'caminho': 'database\\projects data\\10002-CESAN\\10002-CESAN.xlsx', 'arquivo': '10002-CESAN', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'Não definido', 'data_criacao': '23/10/2024 03:51', 'tempo_acesso': '02/01/2025 15:42', 'tempo_modificacao': '02/01/2025 15:42', 'tempo_mudanca': '23/10/2024 03:51', 'tamanho': (10318,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\VIT-REDE-VITÓRIA-R00.xlsx', 'arquivo': 'VIT-REDE-VITÓRIA-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'REDE', 'data_criacao': '25/10/2024 18:18', 'tempo_acesso': '03/11/2024 23:18', 'tempo_modificacao': '03/11/2024 10:19', 'tempo_mudanca': '25/10/2024 18:18', 'tamanho': (10370539,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\VIT-REDE-AV. LEITÃO SILVA-R02.xlsx', 'arquivo': 'VIT-REDE-AV. LEITÃO SILVA-R02', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'REDE', 'data_criacao': '23/10/2024 03:50', 'tempo_acesso': '03/11/2024 23:18', 'tempo_modificacao': '23/10/2024 06:19', 'tempo_mudanca': '23/10/2024 03:50', 'tamanho': (1748848,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-04-26 AV. LEITÃO DA SILVA.xlsx', 'arquivo': 'VIT-TOP-2024-04-26 AV. LEITÃO DA SILVA', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'TOP', 'data_criacao': '13/11/2024 15:07', 'tempo_acesso': '13/11/2024 16:24', 'tempo_modificacao': '13/11/2024 16:24', 'tempo_mudanca': '13/11/2024 15:07', 'tamanho': (51202,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-04-30 SOND LEITÃO DA SILVA.xlsx', 'arquivo': 'VIT-TOP-2024-04-30 SOND LEITÃO DA SILVA', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'TOP', 'data_criacao': '13/11/2024 15:07', 'tempo_acesso': '13/11/2024 15:07', 'tempo_modificacao': '13/11/2024 15:07', 'tempo_mudanca': '13/11/2024 15:07', 'tamanho': (7736,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-06 SOND LEITÃO DA SILVA.xlsx', 'arquivo': 'VIT-TOP-2024-05-06 SOND LEITÃO DA SILVA', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'TOP', 'data_criacao': '13/11/2024 15:07', 'tempo_acesso': '13/11/2024 15:07', 'tempo_modificacao': '13/11/2024 15:07', 'tempo_mudanca': '13/11/2024 15:07', 'tamanho': (7039,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-07 AV. LEITÃO DA SILVA.xlsx', 'arquivo': 'VIT-TOP-2024-05-07 AV. LEITÃO DA SILVA', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'TOP', 'data_criacao': '13/11/2024 15:07', 'tempo_acesso': '13/11/2024 15:08', 'tempo_modificacao': '13/11/2024 15:07', 'tempo_mudanca': '13/11/2024 15:07', 'tamanho': (2243324,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-07 SOND AV. LEITÃO DA SILVA.xlsx', 'arquivo': 'VIT-TOP-2024-05-07 SOND AV. LEITÃO DA SILVA', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'TOP', 'data_criacao': '13/11/2024 15:07', 'tempo_acesso': '13/11/2024 15:08', 'tempo_modificacao': '13/11/2024 15:07', 'tempo_mudanca': '13/11/2024 15:07', 'tamanho': (10174,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-08 SOND AV. LEITÃO DA SILVA.xlsx', 'arquivo': 'VIT-TOP-2024-05-08 SOND AV. LEITÃO DA SILVA', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'TOP', 'data_criacao': '13/11/2024 15:07', 'tempo_acesso': '13/11/2024 15:08', 'tempo_modificacao': '13/11/2024 15:07', 'tempo_mudanca': '13/11/2024 15:07', 'tamanho': (7733,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-28 AV. LEITÃO DA SILVA.xlsx', 'arquivo': 'VIT-TOP-2024-05-28 AV. LEITÃO DA SILVA', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'TOP', 'data_criacao': '13/11/2024 15:07', 'tempo_acesso': '13/11/2024 15:08', 'tempo_modificacao': '13/11/2024 15:07', 'tempo_mudanca': '13/11/2024 15:07', 'tamanho': (226941,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-07-06 AV. LEITÃO DA SILVA.xlsx', 'arquivo': 'VIT-TOP-2024-07-06 AV. LEITÃO DA SILVA', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'TOP', 'data_criacao': '13/11/2024 15:07', 'tempo_acesso': '13/11/2024 15:08', 'tempo_modificacao': '13/11/2024 15:07', 'tempo_mudanca': '13/11/2024 15:07', 'tamanho': (7757,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\03. Cadastros Existentes\\VIT-CAD GERAL-AV. LEITÃO SILVA-R00.xlsx', 'arquivo': 'VIT-CAD GERAL-AV. LEITÃO SILVA-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'CAD', 'data_criacao': '23/10/2024 03:50', 'tempo_acesso': '03/11/2024 23:19', 'tempo_modificacao': '23/10/2024 03:58', 'tempo_mudanca': '23/10/2024 03:50', 'tamanho': (6207868,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\VIT-REDE-AV. LEITÃO SILVA-R01.xlsx', 'arquivo': 'VIT-REDE-AV. LEITÃO SILVA-R01', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'REDE', 'data_criacao': '23/10/2024 03:58', 'tempo_acesso': '03/11/2024 23:19', 'tempo_modificacao': '23/10/2024 03:58', 'tempo_mudanca': '23/10/2024 03:58', 'tamanho': (2501893,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\07. Prefeitura\\VIT-PREF-AV. LEITÃO SILVA-R00.xlsx', 'arquivo': 'VIT-PREF-AV. LEITÃO SILVA-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'PREF', 'data_criacao': '23/10/2024 03:58', 'tempo_acesso': '03/11/2024 23:19', 'tempo_modificacao': '23/10/2024 03:58', 'tempo_mudanca': '23/10/2024 03:58', 'tamanho': (950911,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-04-22\\VIT-MAP-AV. LEITÃO SILVA-R01.xlsx', 'arquivo': 'VIT-MAP-AV. LEITÃO SILVA-R01', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'MAP', 'data_criacao': '23/10/2024 03:58', 'tempo_acesso': '03/11/2024 23:19', 'tempo_modificacao': '23/10/2024 03:58', 'tempo_mudanca': '23/10/2024 03:58', 'tamanho': (126546,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-05-17\\VIT-MAP-2024-05-17-AV. LEITÃO SILVA-R02.xlsx', 'arquivo': 'VIT-MAP-2024-05-17-AV. LEITÃO SILVA-R02', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'MAP', 'data_criacao': '23/10/2024 03:58', 'tempo_acesso': '03/11/2024 23:19', 'tempo_modificacao': '23/10/2024 03:58', 'tempo_mudanca': '23/10/2024 03:58', 'tamanho': (5918853,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-05-17\\VIT-MAP-AV. LEITÃO SILVA-R02.xlsx', 'arquivo': 'VIT-MAP-AV. LEITÃO SILVA-R02', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'MAP', 'data_criacao': '23/10/2024 03:58', 'tempo_acesso': '03/11/2024 23:19', 'tempo_modificacao': '23/10/2024 03:58', 'tempo_mudanca': '23/10/2024 03:58', 'tamanho': (5890015,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-06-15\\VIT-MAP-2024-06-15-AV. LEITÃO SILVA-R03.xlsx', 'arquivo': 'VIT-MAP-2024-06-15-AV. LEITÃO SILVA-R03', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'MAP', 'data_criacao': '23/10/2024 03:59', 'tempo_acesso': '03/11/2024 23:19', 'tempo_modificacao': '23/10/2024 03:59', 'tempo_mudanca': '23/10/2024 03:59', 'tamanho': (5932400,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-07-29\\VIT-MAP-2024-07-29-AV. LEITÃO SILVA-R03.xlsx', 'arquivo': 'VIT-MAP-2024-07-29-AV. LEITÃO SILVA-R03', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'MAP', 'data_criacao': '23/10/2024 03:59', 'tempo_acesso': '03/11/2024 23:19', 'tempo_modificacao': '23/10/2024 03:59', 'tempo_mudanca': '23/10/2024 03:59', 'tamanho': (5913182,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\01. LEITÃO DA SILVA\\11. Cadastro Final\\VIT-CAD-AV. LEITÃO DA SILVA-R01.xlsx', 'arquivo': 'VIT-CAD-AV. LEITÃO DA SILVA-R01', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'CAD', 'data_criacao': '23/10/2024 03:59', 'tempo_acesso': '03/11/2024 23:19', 'tempo_modificacao': '23/10/2024 04:00', 'tempo_mudanca': '23/10/2024 03:59', 'tamanho': (33385073,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\02. MARUÍPE\\00. Planilhas\\VIT-REDE-MARUIPE-R00.xlsx', 'arquivo': 'VIT-REDE-MARUIPE-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'REDE', 'data_criacao': '23/10/2024 04:00', 'tempo_acesso': '03/11/2024 23:19', 'tempo_modificacao': '23/10/2024 04:00', 'tempo_mudanca': '23/10/2024 04:00', 'tamanho': (720590,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\02. MARUÍPE\\01. Rede a Executar\\VIT-REDE-MARUIPE-R00.xlsx', 'arquivo': 'VIT-REDE-MARUIPE-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'REDE', 'data_criacao': '23/10/2024 04:00', 'tempo_acesso': '03/11/2024 23:19', 'tempo_modificacao': '23/10/2024 04:00', 'tempo_mudanca': '23/10/2024 04:00', 'tamanho': (720710,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\01. Rede a Executar\\VIT-REDE-2024-10-21-RETA DA PENHA-R05.xlsx', 'arquivo': 'VIT-REDE-2024-10-21-RETA DA PENHA-R05', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'REDE', 'data_criacao': '08/11/2024 15:52', 'tempo_acesso': '08/11/2024 18:20', 'tempo_modificacao': '08/11/2024 18:20', 'tempo_mudanca': '08/11/2024 15:52', 'tamanho': (915767,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\01. Rede a Executar\\VIT-REDE-PRAIA DO CANTO-R04.xlsx', 'arquivo': 'VIT-REDE-PRAIA DO CANTO-R04', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'REDE', 'data_criacao': '08/11/2024 15:52', 'tempo_acesso': '08/11/2024 18:29', 'tempo_modificacao': '08/11/2024 18:29', 'tempo_mudanca': '08/11/2024 15:52', 'tamanho': (21547076,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM06 - 16.08-15.09\\VIT-MAP-2024-10-21-PRAIA DO CANTO-R04.xlsx', 'arquivo': 'VIT-MAP-2024-10-21-PRAIA DO CANTO-R04', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'MAP', 'data_criacao': '08/11/2024 15:54', 'tempo_acesso': '08/11/2024 18:30', 'tempo_modificacao': '08/11/2024 18:30', 'tempo_mudanca': '08/11/2024 15:54', 'tamanho': (883232,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM06 - 16.08-15.09\\VIT-MAP-2024-10-21-RETA DA PENHA-R04.xlsx', 'arquivo': 'VIT-MAP-2024-10-21-RETA DA PENHA-R04', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'MAP', 'data_criacao': '08/11/2024 15:54', 'tempo_acesso': '08/11/2024 18:30', 'tempo_modificacao': '08/11/2024 18:30', 'tempo_mudanca': '08/11/2024 15:54', 'tamanho': (918720,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM06 - 16.08-15.09\\VIT-MAP-2024-10-21-RETA DA PENHA-R05.xlsx', 'arquivo': 'VIT-MAP-2024-10-21-RETA DA PENHA-R05', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'MAP', 'data_criacao': '08/11/2024 15:54', 'tempo_acesso': '08/11/2024 18:30', 'tempo_modificacao': '08/11/2024 18:30', 'tempo_mudanca': '08/11/2024 15:54', 'tamanho': (916418,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\VIT-MAP-2024-10-21-PRAIA DO CANTO-RAS.xlsx', 'arquivo': 'VIT-MAP-2024-10-21-PRAIA DO CANTO-RAS', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'MAP', 'data_criacao': '08/11/2024 15:54', 'tempo_acesso': '08/11/2024 18:30', 'tempo_modificacao': '08/11/2024 18:30', 'tempo_mudanca': '08/11/2024 15:54', 'tamanho': (1593488,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-01-RB-EST ELEV ESG-R00.xlsx', 'arquivo': 'VIT-RAMAL-01-RB-EST ELEV ESG-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:54', 'tempo_acesso': '08/11/2024 18:30', 'tempo_modificacao': '08/11/2024 18:30', 'tempo_mudanca': '08/11/2024 15:54', 'tamanho': (931583,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-02-RB-C20Z000293-R00.xlsx', 'arquivo': 'VIT-RAMAL-02-RB-C20Z000293-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:55', 'tempo_acesso': '08/11/2024 18:30', 'tempo_modificacao': '08/11/2024 18:30', 'tempo_mudanca': '08/11/2024 15:55', 'tamanho': (1404513,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-03-RB-A20G011517-R00.xlsx', 'arquivo': 'VIT-RAMAL-03-RB-A20G011517-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:55', 'tempo_acesso': '08/11/2024 18:31', 'tempo_modificacao': '08/11/2024 18:31', 'tempo_mudanca': '08/11/2024 15:55', 'tamanho': (1405312,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-04-RB-A22L250499-R00.xlsx', 'arquivo': 'VIT-RAMAL-04-RB-A22L250499-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:55', 'tempo_acesso': '08/11/2024 18:31', 'tempo_modificacao': '08/11/2024 18:31', 'tempo_mudanca': '08/11/2024 15:55', 'tamanho': (1406451,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-05-RB-Y19F919718-R00.xlsx', 'arquivo': 'VIT-RAMAL-05-RB-Y19F919718-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:55', 'tempo_acesso': '08/11/2024 18:31', 'tempo_modificacao': '08/11/2024 18:31', 'tempo_mudanca': '08/11/2024 15:55', 'tamanho': (1400178,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-06-RB-Y20F205143-R00.xlsx', 'arquivo': 'VIT-RAMAL-06-RB-Y20F205143-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:55', 'tempo_acesso': '08/11/2024 18:31', 'tempo_modificacao': '08/11/2024 18:31', 'tempo_mudanca': '08/11/2024 15:55', 'tamanho': (1400181,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-07-RB-Y20L437661-R00.xlsx', 'arquivo': 'VIT-RAMAL-07-RB-Y20L437661-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:55', 'tempo_acesso': '08/11/2024 18:31', 'tempo_modificacao': '08/11/2024 18:31', 'tempo_mudanca': '08/11/2024 15:55', 'tamanho': (925986,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-08-RB-Y22G197286-R00.xlsx', 'arquivo': 'VIT-RAMAL-08-RB-Y22G197286-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:56', 'tempo_acesso': '08/11/2024 18:31', 'tempo_modificacao': '08/11/2024 18:31', 'tempo_mudanca': '08/11/2024 15:56', 'tamanho': (921674,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-09-RB-Y24G053313-R00.xlsx', 'arquivo': 'VIT-RAMAL-09-RB-Y24G053313-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:56', 'tempo_acesso': '08/11/2024 18:32', 'tempo_modificacao': '08/11/2024 18:32', 'tempo_mudanca': '08/11/2024 15:56', 'tamanho': (921665,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-10-RB-A20L592858-R00.xlsx', 'arquivo': 'VIT-RAMAL-10-RB-A20L592858-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:56', 'tempo_acesso': '08/11/2024 18:32', 'tempo_modificacao': '08/11/2024 18:32', 'tempo_mudanca': '08/11/2024 15:56', 'tamanho': (925399,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-11-RB-A24G097763-R00.xlsx', 'arquivo': 'VIT-RAMAL-11-RB-A24G097763-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:56', 'tempo_acesso': '08/11/2024 18:32', 'tempo_modificacao': '08/11/2024 18:32', 'tempo_mudanca': '08/11/2024 15:56', 'tamanho': (923397,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-12-RB-E22DM2003209-R00.xlsx', 'arquivo': 'VIT-RAMAL-12-RB-E22DM2003209-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:56', 'tempo_acesso': '08/11/2024 18:32', 'tempo_modificacao': '08/11/2024 18:32', 'tempo_mudanca': '08/11/2024 15:56', 'tamanho': (1008022,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-13-DP-Y21L019893-R00.xlsx', 'arquivo': 'VIT-RAMAL-13-DP-Y21L019893-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:56', 'tempo_acesso': '08/11/2024 18:32', 'tempo_modificacao': '08/11/2024 18:32', 'tempo_mudanca': '08/11/2024 15:56', 'tamanho': (1404413,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-14-DP-Y21L0004567-R00.xlsx', 'arquivo': 'VIT-RAMAL-14-DP-Y21L0004567-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:56', 'tempo_acesso': '08/11/2024 18:32', 'tempo_modificacao': '08/11/2024 18:32', 'tempo_mudanca': '08/11/2024 15:56', 'tamanho': (1415142,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-15-DP-Y21L004191-R00.xlsx', 'arquivo': 'VIT-RAMAL-15-DP-Y21L004191-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:57', 'tempo_acesso': '08/11/2024 18:33', 'tempo_modificacao': '08/11/2024 18:33', 'tempo_mudanca': '08/11/2024 15:57', 'tamanho': (1419037,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-16-DP-A24G097767-R00.xlsx', 'arquivo': 'VIT-RAMAL-16-DP-A24G097767-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:57', 'tempo_acesso': '08/11/2024 18:33', 'tempo_modificacao': '08/11/2024 18:33', 'tempo_mudanca': '08/11/2024 15:57', 'tamanho': (1414257,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-17-DP-C20ZR00372-R00.xlsx', 'arquivo': 'VIT-RAMAL-17-DP-C20ZR00372-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:57', 'tempo_acesso': '08/11/2024 18:33', 'tempo_modificacao': '08/11/2024 18:33', 'tempo_mudanca': '08/11/2024 15:57', 'tamanho': (1414831,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-18-DP-A21F182900-R00.xlsx', 'arquivo': 'VIT-RAMAL-18-DP-A21F182900-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:57', 'tempo_acesso': '08/11/2024 18:33', 'tempo_modificacao': '08/11/2024 18:33', 'tempo_mudanca': '08/11/2024 15:57', 'tamanho': (1414811,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-19-DP-Y19L361086-R00.xlsx', 'arquivo': 'VIT-RAMAL-19-DP-Y19L361086-R00', 'tipo_arquivo': '.xlsx', 'tipo_proj': 'RAMAL', 'data_criacao': '08/11/2024 15:57', 'tempo_acesso': '08/11/2024 18:33', 'tempo_modificacao': '08/11/2024 18:33', 'tempo_mudanca': '08/11/2024 15:57', 'tamanho': (1415660,)}, {'caminho': 'database\\projects data\\10002-CESAN\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\RAMAIS\\VIT-RAMAL-20-DP-D22DM200

,caminho,arquivo,tipo_arquivo,tipo_proj,data_criacao,tempo_acesso,tempo_modificacao,tempo_mudanca,tamanho,tamanho_kb
0,database\projects data\10002-CESAN\10002-CESAN...,10002-CESAN,.xlsx,Não definido,23/10/2024 03:51,02/01/2025 15:42,02/01/2025 15:42,23/10/2024 03:51,10318,10.08
1,database\projects data\10002-CESAN\02. VITÓRIA...,VIT-REDE-VITÓRIA-R00,.xlsx,REDE,25/10/2024 18:18,03/11/2024 23:18,03/11/2024 10:19,25/10/2024 18:18,10370539,10127.48
2,database\projects data\10002-CESAN\02. VITÓRIA...,VIT-REDE-AV. LEITÃO SILVA-R02,.xlsx,REDE,23/10/2024 03:50,03/11/2024 23:18,23/10/2024 06:19,23/10/2024 03:50,1748848,1707.86
3,database\projects data\10002-CESAN\02. VITÓRIA...,VIT-TOP-2024-04-26 AV. LEITÃO DA SILVA,.xlsx,TOP,13/11/2024 15:07,13/11/2024 16:24,13/11/2024 16:24,13/11/2024 15:07,51202,50.00
4,database\projects data\10002-CESAN\02. VITÓRIA...,VIT-TOP-2024-04-30 SOND LEITÃO DA SILVA,.xlsx,TOP,13/11/2024 15:07,13/11/2024 15:07,13/11/2024 15:07,13/11/2024 15:07,7736,7.55
...,...,...,...,...,...,...,...,...,...,...
183,database\projects data\10002-CESAN-25\03. VILA...,2024-12-26 JM Vila Velha_REDE,.xlsx,Não definido,02/01/2025 15:32,02/01/2025 15:33,02/01/2025 15:32,02/01/2025 15:32,43773,42.75
184,database\projects data\10002-CESAN-25\03. VILA...,2024-12-26 NO Vila Velha_REDE,.xlsx,Não definido,02/01/2025 15:32,02/01/2025 15:33,02/01/2025 15:32,02/01/2025 15:32,14411,14.07
185,database\projects data\10002-CESAN-25\03. VILA...,2024-12-26 NS Vila Velha_REDE,.xlsx,Não definido,02/01/2025 15:32,02/01/2025 15:33,02/01/2025 15:32,02/01/2025 15:32,21286,20.79
186,database\projects data\10002-CESAN-25\03. VILA...,2024-12-26 Paraguassu Vila Velha_REDE,.xlsx,Não definido,02/01/2025 15:32,02/01/2025 15:33,02/01/2025 15:32,02/01/2025 15:32,13200,12.89
187,database\projects data\10002-CESAN-25\04. GUAR...,VIT-REDE-GUARAPARI-R04,.xlsx,REDE,02/01/2025 15:36,02/01/2025 15:45,02/01/2025 15:42,02/01/2025 15:36,59065169,57680.83

['.xlsx']

109it [00:00, 2436.85it/s]

[{'caminho': 'database\\projects\\10002-CESAN-25\\00. RECEBIDOS\\01. Vitória\\06. SERAFIM DERENZE\\VIT-REDE-SERAFIM DERENZE-R00.dxf', 'arquivo': 'VIT-REDE-SERAFIM DERENZE-R00', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 16:04', 'tempo_acesso': '02/01/2025 16:06', 'tempo_modificacao': '02/01/2025 16:06', 'tempo_mudanca': '02/01/2025 16:04', 'tamanho': (425582142,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\VIT-REDE-VITÓRIA-R00.dxf', 'arquivo': 'VIT-REDE-VITÓRIA-R00', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 16:16', 'tempo_acesso': '02/01/2025 16:16', 'tempo_modificacao': '02/01/2025 16:16', 'tempo_mudanca': '02/01/2025 16:16', 'tamanho': (36020383,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-04-26 AV. LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-04-26 AV. LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'tipo_proj': 'TOP', 'data_criacao': '02/01/2025 16:06', 'tempo_acesso': '02/01/2025 16:06', 'tempo_modificacao': '02/01/2025 16:06', 'tempo_mudanca': '02/01/2025 16:06', 'tamanho': (510732,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-04-30 SOND LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-04-30 SOND LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'tipo_proj': 'TOP', 'data_criacao': '02/01/2025 16:06', 'tempo_acesso': '02/01/2025 16:06', 'tempo_modificacao': '02/01/2025 16:06', 'tempo_mudanca': '02/01/2025 16:06', 'tamanho': (314786,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-06 SOND LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-05-06 SOND LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'tipo_proj': 'TOP', 'data_criacao': '02/01/2025 16:06', 'tempo_acesso': '02/01/2025 16:06', 'tempo_modificacao': '02/01/2025 16:06', 'tempo_mudanca': '02/01/2025 16:06', 'tamanho': (359462,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-07 AV. LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-05-07 AV. LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'tipo_proj': 'TOP', 'data_criacao': '02/01/2025 16:06', 'tempo_acesso': '02/01/2025 16:06', 'tempo_modificacao': '02/01/2025 16:06', 'tempo_mudanca': '02/01/2025 16:06', 'tamanho': (3849120,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-07 SOND AV. LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-05-07 SOND AV. LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'tipo_proj': 'TOP', 'data_criacao': '02/01/2025 16:06', 'tempo_acesso': '02/01/2025 16:06', 'tempo_modificacao': '02/01/2025 16:06', 'tempo_mudanca': '02/01/2025 16:06', 'tamanho': (371432,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-08 SOND AV. LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-05-08 SOND AV. LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'tipo_proj': 'TOP', 'data_criacao': '02/01/2025 16:06', 'tempo_acesso': '02/01/2025 16:06', 'tempo_modificacao': '02/01/2025 16:06', 'tempo_mudanca': '02/01/2025 16:06', 'tamanho': (362104,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-05-28 AV. LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-05-28 AV. LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'tipo_proj': 'TOP', 'data_criacao': '02/01/2025 16:06', 'tempo_acesso': '02/01/2025 16:06', 'tempo_modificacao': '02/01/2025 16:06', 'tempo_mudanca': '02/01/2025 16:06', 'tamanho': (1146619,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\02. Topografia\\VIT-TOP-2024-07-06 AV. LEITÃO DA SILVA.dxf', 'arquivo': 'VIT-TOP-2024-07-06 AV. LEITÃO DA SILVA', 'tipo_arquivo': '.dxf', 'tipo_proj': 'TOP', 'data_criacao': '02/01/2025 16:06', 'tempo_acesso': '02/01/2025 16:06', 'tempo_modificacao': '02/01/2025 16:06', 'tempo_mudanca': '02/01/2025 16:06', 'tamanho': (364982,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\03. Cadastros Existentes\\VIT-CAD GERAL-AV. LEITÃO DA SILVA-R00.dxf', 'arquivo': 'VIT-CAD GERAL-AV. LEITÃO DA SILVA-R00', 'tipo_arquivo': '.dxf', 'tipo_proj': 'CAD', 'data_criacao': '02/01/2025 16:06', 'tempo_acesso': '02/01/2025 16:06', 'tempo_modificacao': '02/01/2025 16:06', 'tempo_mudanca': '02/01/2025 16:06', 'tamanho': (28016058,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\VIT-REDE-AV. LEITÃO DA SILVA-R05.dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R05', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 15:21', 'tempo_acesso': '02/01/2025 16:07', 'tempo_modificacao': '02/01/2025 16:07', 'tempo_mudanca': '02/01/2025 15:21', 'tamanho': (27798443,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\01. Estudo\\VIT-REDE-AV. LEITÃO DA SILVA-R00.dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R00', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 16:06', 'tempo_acesso': '02/01/2025 16:06', 'tempo_modificacao': '02/01/2025 16:06', 'tempo_mudanca': '02/01/2025 16:06', 'tamanho': (2586902,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\R01\\VIT-REDE-AV. LEITÃO DA SILVA-R01.dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R01', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 16:06', 'tempo_acesso': '02/01/2025 16:07', 'tempo_modificacao': '02/01/2025 16:07', 'tempo_mudanca': '02/01/2025 16:06', 'tamanho': (9480990,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\R02\\VIT-REDE-AV. LEITÃO DA SILVA-R02.dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R02', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 16:07', 'tempo_acesso': '02/01/2025 16:07', 'tempo_modificacao': '02/01/2025 16:07', 'tempo_mudanca': '02/01/2025 16:07', 'tamanho': (12626872,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\R03\\VIT-REDE-AV. LEITÃO DA SILVA-R03 (CAMPO).dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R03 (CAMPO)', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 16:07', 'tempo_acesso': '02/01/2025 16:07', 'tempo_modificacao': '02/01/2025 16:07', 'tempo_mudanca': '02/01/2025 16:07', 'tamanho': (10665606,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\R03\\VIT-REDE-AV. LEITÃO DA SILVA-R03.0.dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R03.0', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 15:20', 'tempo_acesso': '02/01/2025 16:07', 'tempo_modificacao': '02/01/2025 16:07', 'tempo_mudanca': '02/01/2025 15:20', 'tamanho': (10589535,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\R03\\VIT-REDE-AV. LEITÃO DA SILVA-R04.1.dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R04.1', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 15:20', 'tempo_acesso': '02/01/2025 16:07', 'tempo_modificacao': '02/01/2025 16:07', 'tempo_mudanca': '02/01/2025 15:20', 'tamanho': (10593138,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\06. Rede a Executar\\R04\\VIT-REDE-AV. LEITÃO DA SILVA-R04.0.dxf', 'arquivo': 'VIT-REDE-AV. LEITÃO DA SILVA-R04.0', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 15:20', 'tempo_acesso': '02/01/2025 16:07', 'tempo_modificacao': '02/01/2025 16:07', 'tempo_mudanca': '02/01/2025 15:20', 'tamanho': (27668875,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\07. Prefeitura\\VIT-PREF-AV. LEITÃO DA SILVA-R00.dxf', 'arquivo': 'VIT-PREF-AV. LEITÃO DA SILVA-R00', 'tipo_arquivo': '.dxf', 'tipo_proj': 'PREF', 'data_criacao': '02/01/2025 16:07', 'tempo_acesso': '02/01/2025 16:07', 'tempo_modificacao': '02/01/2025 16:07', 'tempo_mudanca': '02/01/2025 16:07', 'tamanho': (2586902,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-04-22\\VIT-MAP-AV. LEITÃO DA SILVA-R01.dxf', 'arquivo': 'VIT-MAP-AV. LEITÃO DA SILVA-R01', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:07', 'tempo_acesso': '02/01/2025 16:07', 'tempo_modificacao': '02/01/2025 16:07', 'tempo_mudanca': '02/01/2025 16:07', 'tamanho': (1068466,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-05-17\\VIT-MAP-2024-05-17-AV. LEITÃO DA SILVA-R02.dxf', 'arquivo': 'VIT-MAP-2024-05-17-AV. LEITÃO DA SILVA-R02', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:07', 'tempo_acesso': '02/01/2025 16:07', 'tempo_modificacao': '02/01/2025 16:07', 'tempo_mudanca': '02/01/2025 16:07', 'tamanho': (27560483,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-05-17\\VIT-MAP-AV. LEITÃO DA SILVA-R02.dxf', 'arquivo': 'VIT-MAP-AV. LEITÃO DA SILVA-R02', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:08', 'tempo_acesso': '02/01/2025 16:08', 'tempo_modificacao': '02/01/2025 16:08', 'tempo_mudanca': '02/01/2025 16:08', 'tamanho': (27559383,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-06-15\\VIT-MAP-2024-06-15-AV. LEITÃO DA SILVA-R03.dxf', 'arquivo': 'VIT-MAP-2024-06-15-AV. LEITÃO DA SILVA-R03', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:08', 'tempo_acesso': '02/01/2025 16:08', 'tempo_modificacao': '02/01/2025 16:08', 'tempo_mudanca': '02/01/2025 16:08', 'tamanho': (27495650,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\10. Mapa Iluminado\\MAP - 2024-07-29\\VIT-MAP-2024-07-29-AV. LEITÃO DA SILVA-R03.dxf', 'arquivo': 'VIT-MAP-2024-07-29-AV. LEITÃO DA SILVA-R03', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:08', 'tempo_acesso': '02/01/2025 16:08', 'tempo_modificacao': '02/01/2025 16:08', 'tempo_mudanca': '02/01/2025 16:08', 'tamanho': (27558045,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\01. LEITÃO DA SILVA\\11. Cadastro Final\\VIT-CAD-AV. LEITÃO DA SILVA-R01.dxf', 'arquivo': 'VIT-CAD-AV. LEITÃO DA SILVA-R01', 'tipo_arquivo': '.dxf', 'tipo_proj': 'CAD', 'data_criacao': '02/01/2025 16:08', 'tempo_acesso': '02/01/2025 16:09', 'tempo_modificacao': '02/01/2025 16:09', 'tempo_mudanca': '02/01/2025 16:08', 'tamanho': (64077432,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\02. MARUÍPE\\VIT-REDE-MARUIPE-R01.dxf', 'arquivo': 'VIT-REDE-MARUIPE-R01', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 15:21', 'tempo_acesso': '02/01/2025 16:09', 'tempo_modificacao': '02/01/2025 16:09', 'tempo_mudanca': '02/01/2025 15:21', 'tamanho': (64794656,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\02. MARUÍPE\\01. Rede a Executar\\VIT-REDE-MARUIPE-R00.dxf', 'arquivo': 'VIT-REDE-MARUIPE-R00', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 15:21', 'tempo_acesso': '02/01/2025 16:09', 'tempo_modificacao': '02/01/2025 16:09', 'tempo_mudanca': '02/01/2025 15:21', 'tamanho': (6553123,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\01. Rede a Executar\\VIT-REDE-2024-10-21-RETA DA PENHA-R05.dxf', 'arquivo': 'VIT-REDE-2024-10-21-RETA DA PENHA-R05', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 16:09', 'tempo_acesso': '02/01/2025 16:09', 'tempo_modificacao': '02/01/2025 16:09', 'tempo_mudanca': '02/01/2025 16:09', 'tamanho': (13307603,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\01. Rede a Executar\\VIT-REDE-PRAIA DO CANTO-R04.dxf', 'arquivo': 'VIT-REDE-PRAIA DO CANTO-R04', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 16:09', 'tempo_acesso': '02/01/2025 16:10', 'tempo_modificacao': '02/01/2025 16:10', 'tempo_mudanca': '02/01/2025 16:09', 'tamanho': (97230279,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM06 - 16.08-15.09\\VIT-MAP-2024-10-21-PRAIA DO CANTO-R04.dxf', 'arquivo': 'VIT-MAP-2024-10-21-PRAIA DO CANTO-R04', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:10', 'tempo_acesso': '02/01/2025 16:10', 'tempo_modificacao': '02/01/2025 16:10', 'tempo_mudanca': '02/01/2025 16:10', 'tamanho': (12858117,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM06 - 16.08-15.09\\VIT-MAP-2024-10-21-RETA DA PENHA-R04.dxf', 'arquivo': 'VIT-MAP-2024-10-21-RETA DA PENHA-R04', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:10', 'tempo_acesso': '02/01/2025 16:10', 'tempo_modificacao': '02/01/2025 16:10', 'tempo_mudanca': '02/01/2025 16:10', 'tamanho': (13278522,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM06 - 16.08-15.09\\VIT-MAP-2024-10-21-RETA DA PENHA-R05.dxf', 'arquivo': 'VIT-MAP-2024-10-21-RETA DA PENHA-R05', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:10', 'tempo_acesso': '02/01/2025 16:10', 'tempo_modificacao': '02/01/2025 16:10', 'tempo_mudanca': '02/01/2025 16:10', 'tamanho': (13306790,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\BM07 - 16.09-15.10\\VIT-MAP-2024-10-21-PRAIA DO CANTO-RAS.dxf', 'arquivo': 'VIT-MAP-2024-10-21-PRAIA DO CANTO-RAS', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:10', 'tempo_acesso': '02/01/2025 16:10', 'tempo_modificacao': '02/01/2025 16:10', 'tempo_mudanca': '02/01/2025 16:10', 'tamanho': (16877341,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\MAP - 2024-06-19\\VIT-MAP-2024-06-19-HDD BLOCO 01-R03.dxf', 'arquivo': 'VIT-MAP-2024-06-19-HDD BLOCO 01-R03', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:10', 'tempo_acesso': '02/01/2025 16:10', 'tempo_modificacao': '02/01/2025 16:10', 'tempo_mudanca': '02/01/2025 16:10', 'tamanho': (105545948,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\MAP - 2024-06-24\\VIT-MAP-2024-06-24-HDD BLOCO 01-R03.dxf', 'arquivo': 'VIT-MAP-2024-06-24-HDD BLOCO 01-R03', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:10', 'tempo_acesso': '02/01/2025 16:10', 'tempo_modificacao': '02/01/2025 16:10', 'tempo_mudanca': '02/01/2025 16:10', 'tamanho': (41915420,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\MAP - 2024-08-30\\VIT-MAP-2024-08-30-PIPE BLOCO 01-R03.1.dxf', 'arquivo': 'VIT-MAP-2024-08-30-PIPE BLOCO 01-R03.1', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:10', 'tempo_acesso': '02/01/2025 16:10', 'tempo_modificacao': '02/01/2025 16:10', 'tempo_mudanca': '02/01/2025 16:10', 'tamanho': (63618063,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\MAP - 2024-08-30\\VIT-MAP-2024-08-30-PIPE BLOCO 01-R03.dxf', 'arquivo': 'VIT-MAP-2024-08-30-PIPE BLOCO 01-R03', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:10', 'tempo_acesso': '02/01/2025 16:11', 'tempo_modificacao': '02/01/2025 16:11', 'tempo_mudanca': '02/01/2025 16:10', 'tamanho': (63608542,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\MAP - 2024-09-20\\VIT-MAP-PRAIA DO CANTO-R04.dxf', 'arquivo': 'VIT-MAP-PRAIA DO CANTO-R04', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:11', 'tempo_acesso': '02/01/2025 16:11', 'tempo_modificacao': '02/01/2025 16:11', 'tempo_mudanca': '02/01/2025 16:11', 'tamanho': (95584957,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\02. Mapa Iluminado\\MAP - 2024-10-02\\VIT-MAP-2024-10-02-PRAIA DO CANTO-R04 COM RAMAIS.dxf', 'arquivo': 'VIT-MAP-2024-10-02-PRAIA DO CANTO-R04 COM RAMAIS', 'tipo_arquivo': '.dxf', 'tipo_proj': 'MAP', 'data_criacao': '02/01/2025 16:11', 'tempo_acesso': '02/01/2025 16:11', 'tempo_modificacao': '02/01/2025 16:11', 'tempo_mudanca': '02/01/2025 16:11', 'tamanho': (97766161,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\03. Cadastro\\VIT-CAD-2024-09-27-DOM PEDRO A RIO BRANCO-R04.dxf', 'arquivo': 'VIT-CAD-2024-09-27-DOM PEDRO A RIO BRANCO-R04', 'tipo_arquivo': '.dxf', 'tipo_proj': 'CAD', 'data_criacao': '02/01/2025 16:11', 'tempo_acesso': '02/01/2025 16:11', 'tempo_modificacao': '02/01/2025 16:11', 'tempo_mudanca': '02/01/2025 16:11', 'tamanho': (45703903,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\03. Cadastro\\02. Topografia\\VIT-TOP-2024-07-01-BLOCO 1 HDD-R00.dxf', 'arquivo': 'VIT-TOP-2024-07-01-BLOCO 1 HDD-R00', 'tipo_arquivo': '.dxf', 'tipo_proj': 'TOP', 'data_criacao': '02/01/2025 16:11', 'tempo_acesso': '02/01/2025 16:11', 'tempo_modificacao': '02/01/2025 16:11', 'tempo_mudanca': '02/01/2025 16:11', 'tamanho': (387250,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\03. Cadastro\\02. Topografia\\VIT-TOP-2024-07-01-DOM PEDRO II-R00.dxf', 'arquivo': 'VIT-TOP-2024-07-01-DOM PEDRO II-R00', 'tipo_arquivo': '.dxf', 'tipo_proj': 'TOP', 'data_criacao': '02/01/2025 16:11', 'tempo_acesso': '02/01/2025 16:11', 'tempo_modificacao': '02/01/2025 16:11', 'tempo_mudanca': '02/01/2025 16:11', 'tamanho': (333942,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\03. Cadastro\\02. Topografia\\VIT-TOP-2024-07-01-JOÃO DA CRUZ-R00.dxf', 'arquivo': 'VIT-TOP-2024-07-01-JOÃO DA CRUZ-R00', 'tipo_arquivo': '.dxf', 'tipo_proj': 'TOP', 'data_criacao': '02/01/2025 16:11', 'tempo_acesso': '02/01/2025 16:11', 'tempo_modificacao': '02/01/2025 16:11', 'tempo_mudanca': '02/01/2025 16:11', 'tamanho': (389837,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\03. Cadastro\\02. Topografia\\VIT-TOP-2024-07-01-praia do canto.dxf', 'arquivo': 'VIT-TOP-2024-07-01-praia do canto', 'tipo_arquivo': '.dxf', 'tipo_proj': 'TOP', 'data_criacao': '02/01/2025 16:11', 'tempo_acesso': '02/01/2025 16:11', 'tempo_modificacao': '02/01/2025 16:11', 'tempo_mudanca': '02/01/2025 16:11', 'tamanho': (347548,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\04. Complementares\\07. Prefeitura\\VIT-PREF-BLOCO 2-R03.dxf', 'arquivo': 'VIT-PREF-BLOCO 2-R03', 'tipo_arquivo': '.dxf', 'tipo_proj': 'PREF', 'data_criacao': '02/01/2025 16:11', 'tempo_acesso': '02/01/2025 16:11', 'tempo_modificacao': '02/01/2025 16:11', 'tempo_mudanca': '02/01/2025 16:11', 'tamanho': (94386345,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\05. Antigo\\R00\\VIT-REDE-PRAIA DO CANTO-R00.dxf', 'arquivo': 'VIT-REDE-PRAIA DO CANTO-R00', 'tipo_arquivo': '.dxf', 'tipo_proj': 'REDE', 'data_criacao': '02/01/2025 16:11', 'tempo_acesso': '02/01/2025 16:12', 'tempo_modificacao': '02/01/2025 16:12', 'tempo_mudanca': '02/01/2025 16:11', 'tamanho': (447468539,)}, {'caminho': 'database\\projects\\10002-CESAN-25\\02. VITÓRIA\\03. PRAIA DO CANTO\\05. Antigo\\R01\\VIT-PREF-BL01 PIPE-R03.dxf', 'arquivo': 'VIT-PREF-BL01 PIPE-R03', 'tipo_arquivo': '.dxf', 'tipo_proj': 'PREF', 'data_criacao': '02/01/2025 16:12', 'tempo_acesso': '02/01/2025 16:12', 'tempo_modificacao': '02/01/2025 16:12', 'tempo_mudanca': '02/01/2025 1

,caminho,arquivo,tipo_arquivo,tipo_proj,data_criacao,tempo_acesso,tempo_modificacao,tempo_mudanca,tamanho,tamanho_kb
0,database\projects\10002-CESAN-25\00. RECEBIDOS...,VIT-REDE-SERAFIM DERENZE-R00,.dxf,REDE,02/01/2025 16:04,02/01/2025 16:06,02/01/2025 16:06,02/01/2025 16:04,425582142,415607.56
1,database\projects\10002-CESAN-25\02. VITÓRIA\V...,VIT-REDE-VITÓRIA-R00,.dxf,REDE,02/01/2025 16:16,02/01/2025 16:16,02/01/2025 16:16,02/01/2025 16:16,36020383,35176.16
2,database\projects\10002-CESAN-25\02. VITÓRIA\0...,VIT-TOP-2024-04-26 AV. LEITÃO DA SILVA,.dxf,TOP,02/01/2025 16:06,02/01/2025 16:06,02/01/2025 16:06,02/01/2025 16:06,510732,498.76
3,database\projects\10002-CESAN-25\02. VITÓRIA\0...,VIT-TOP-2024-04-30 SOND LEITÃO DA SILVA,.dxf,TOP,02/01/2025 16:06,02/01/2025 16:06,02/01/2025 16:06,02/01/2025 16:06,314786,307.41
4,database\projects\10002-CESAN-25\02. VITÓRIA\0...,VIT-TOP-2024-05-06 SOND LEITÃO DA SILVA,.dxf,TOP,02/01/2025 16:06,02/01/2025 16:06,02/01/2025 16:06,02/01/2025 16:06,359462,351.04
...,...,...,...,...,...,...,...,...,...,...
176,database\projects\10002-CESAN-25\07. ARACRUZ\V...,VIT-TOP-ARACRUZ-R01,.dxf,TOP,02/01/2025 16:48,03/01/2025 08:25,02/01/2025 16:48,02/01/2025 16:48,12078288,11795.20
177,database\projects\10002-CESAN-25\07. ARACRUZ\V...,VIT-TOP-ARACRUZ-R02,.dxf,TOP,02/01/2025 16:48,03/01/2025 08:25,02/01/2025 16:48,02/01/2025 16:48,12068988,11786.12
178,database\projects\10002-CESAN-25\07. ARACRUZ\V...,VIT-TOP-ARACRUZ-R03,.dxf,TOP,02/01/2025 16:48,03/01/2025 08:25,02/01/2025 16:48,02/01/2025 16:48,12101083,11817.46
179,database\projects\10002-CESAN-25\07. ARACRUZ\0...,VIT-TOP-2024-09-20-ARACRUZ-R01,.dxf,TOP,02/01/2025 16:48,03/01/2025 08:25,02/01/2025 16:48,02/01/2025 16:48,4941108,4825.30
180,database\projects\10002-CESAN-25\07. ARACRUZ\0...,VIT-TOP-ARACRUZ-R00,.dxf,TOP,02/01/2025 16:48,03/01/2025 08:25,02/01/2025 16:48,02/01/2025 16:48,9205845,8990.08

2it [00:00, 16.58it/s]

['.dxf']

In [16]:
df = informacoes_df
df[['caminho', 'arquivo']]

,caminho,arquivo
0,database\projects\10002-CESAN-25\00. RECEBIDOS...,VIT-REDE-SERAFIM DERENZE-R00
115,database\projects\10002-CESAN-25\03. VILA VELH...,VIT-TOP-2024-12-05-Vila Velha
116,database\projects\10002-CESAN-25\03. VILA VELH...,VIT-TOP-2024-12-06-CARLOS LINDENBERG-R07
117,database\projects\10002-CESAN-25\03. VILA VELH...,VIT-TOP-2024-12-06-JERONIMO MONTEIRO-R07
118,database\projects\10002-CESAN-25\03. VILA VELH...,VIT-TOP-2024-12-12-CARLOS LINDENBERG-R07 ESTACAS
...,...,...
62,database\projects\10002-CESAN-25\02. VITÓRIA\0...,VIT-REDE-000-CENTRO-R00 (ORÇAMENTO)
63,database\projects\10002-CESAN-25\02. VITÓRIA\0...,VIT-REDE-000-CENTRO-R00
64,database\projects\10002-CESAN-25\02. VITÓRIA\0...,VIT-REDE-000-CENTRO-R01
66,database\projects\10002-CESAN-25\02. VITÓRIA\0...,VIT-REDE-000-CENTRO-R03
180,database\projects\10002-CESAN-25\07. ARACRUZ\0...,VIT-TOP-ARACRUZ-R00

In [17]:
df.to_excel('tmp/projetos_origem.xlsx', index=False)